<aside class="control-sidebar control-sidebar-light">
    <ul class="sidebar-menu">
        <li class="<?= $this->side_pemda ?>"><a href="<?= $this->url('setting_pemda') ?> "><i class="fa fa-circle text-orange"></i><span> Pemerintah Daerah</span></a></li>
        <li class="<?= $this->side_pejabat ?>"><a href="<?= $this->url('setting_pejabat_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Pejabat</span></a></li>        
        <li class="<?= $this->side_notaris ?>"><a href="<?= $this->url('setting_notaris_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Pejabat Notaris/PPAT</span></a></li>        
        <li class="<?= $this->side_jenis_transaksi ?>"><a href="<?= $this->url('setting_jenis_transaksi_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Jenis Transaksi</span></a></li>        
        <li class="<?= $this->side_npotkp ?>"><a href="<?= $this->url('setting_tarif_npotkp') ?> "><i class="fa fa-circle text-orange"></i><span> Tarif NPOTKP</span></a></li>
        <li class="<?= $this->side_tarifbphtb ?>"><a href="<?= $this->url('setting_tarif_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Tarif BPHTB</span></a></li>
        <li class="<?= $this->side_haktanah ?>"><a href="<?= $this->url('setting_hak_tanah') ?> "><i class="fa fa-circle text-orange"></i><span> Hak Tanah</span></a></li>                
        <li class="<?= $this->side_persyaratan_transaksi ?>"><a href="<?= $this->url('setting_persyaratan_transaksi_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Persyaratan Transaksi</span></a></li>                
        <li class="<?= $this->side_dokumen_tanah ?>"><a href="<?= $this->url('setting_dokumen_tanah_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Jenis Dokumen Tanah</span></a></li>                
        <li class="<?= $this->side_harga_acuan ?>"><a href="<?= $this->url('setting_harga_acuan_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Harga Acuan Tanah</span></a></li>                       
        <li class="<?= $this->side_kecamatan ?>"><a href="<?= $this->url('setting_kecamatan_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Kecamatan</span></a></li>               
        <li class="<?= $this->side_kelurahan ?>"><a href="<?= $this->url('setting_kelurahan_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Kelurahan</span></a></li>               
        <li class="<?= $this->side_target ?>"><a href="<?= $this->url('setting_target') ?> "><i class="fa fa-circle text-orange"></i><span> Target Anggaran</span></a></li>               
        <li class="<?= $this->side_pengguna ?>"><a href="<?= $this->url('setting_user_bphtb') ?> "><i class="fa fa-circle text-orange"></i><span> Pengguna</span></a></li>
        <li class="<?= $this->side_historylog ?>"><a href="<?= $this->url('historylog') ?> "><i class="fa fa-circle text-orange"></i><span> History Log</span></a></li>
        <li class="<?= $this->side_password_pengguna ?>"><a href="<?= $this->url('setting_user_bphtb') . '/ubahpass' ?> "><i class="fa fa-circle text-orange"></i><span> Ubah Password</span></a></li>
    </ul>
</aside>