<html moznomarginboxes mozdisallowselectionprint>
    <head>
        <style type="text/css">
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }

            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 8pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    

            .font_empatbelas {
                font-size: 14pt;
            }    
        </style>
    </head>
    <body>
        <?php
        ini_set("max_execution_time", 5000);
        ini_set('memory_limit', '1024M');
        ?>
        <div class="printarea">
            <div id='outerdiv'>
                <div style='width: 10%; float: left;'>
                    <img src="http://<?= $_SERVER['HTTP_HOST']; ?>/<?= $this->basePath(); ?>/<?= $ar_pemda->s_logo ?>"style="height: 75px;">
                </div>
                <div style='width: 90%; float: right;'>
                    <p style="text-align: center; font-size: 14pt; font-weight: BOLD;">
                        PEMERINTAH <?= strtoupper($ar_pemda->s_namakabkot); ?>, <?= strtoupper($ar_pemda->s_namaprov); ?>
                    </p>
                    <p style="text-align: center; font-size: 16pt; font-weight: BOLD; line-height: 1px;">
                        <?= strtoupper($ar_pemda->s_namainstansi); ?> (<?= strtoupper($ar_pemda->s_namasingkatinstansi); ?>)
                    </p>
                    <p style="text-align: center; font-size: 12pt; line-height: 5px">
                        <?= strtoupper($ar_pemda->s_alamatinstansi); ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>, <?= $ar_pemda->s_namaibukotakabkot ?> <?= $ar_pemda->s_kodepos ?>
                    </p>
                </div>
                <div style='clear:both;'></div>
            </div>
            <hr style="line-height: 1px; color: black">
            <h2 style="text-align: center">DAFTAR SSPD BPHTB YANG TELAH VALIDASI</h2>
            <div id='outerdiv'>
                <div style='width: 20%; float: left;'>
                    Tanggal Cetak
                </div>
                <div style='width: 80%; float: right;'>
                    : <?= $tgl_cetak ?>
                </div>
            </div>
            <div id='outerdiv'>
                <div style='width: 20%; float: left;'>
                    Tanggal Validasi
                </div>
                <div style='width: 80%; float: right;'>
                    : <?= $tgl_verifikasi1 ?> s/d <?= $tgl_verifikasi2 ?>
                </div>
            </div>
            <table width="100%" style="border-spacing: 0" class="font_empatbelas">
                <tr style="text-align: center">
                    <td rowspan="3">
                        No.
                    </td>
                    <td rowspan="3">
                        No. Daftar
                    </td>
                    <td rowspan="1" colspan="2">
                        Yang Menerima Hak
                    </td>
                    <td rowspan="1" colspan="9">
                        Berdasarkan SSPD Lembar ke-3
                    </td>
                    <td rowspan="1" colspan="3">
                        Pembayaran BPHTB
                    </td>
                    <td rowspan="3">
                        Tanggal Validasi
                    </td>
                </tr>
                <tr style="text-align: center">
                    <td rowspan="2" colspan="1">
                        Nama
                    </td>
                    <td rowspan="2" colspan="1">
                        Alamat
                    </td>
                    <td rowspan="2" colspan="1">
                        Harga Transaksi
                    </td>
                    <td rowspan="1" colspan="2">
                        Bumi
                    </td>
                    <td rowspan="1" colspan="2">
                        Bangunan
                    </td>
                    <td rowspan="2" colspan="1">
                        NJOP Total
                    </td>
                    <td rowspan="2" colspan="1">
                        NPOP
                    </td>
                    <td rowspan="2" colspan="1">
                        NPOPTKP
                    </td>
                    <td rowspan="2" colspan="1">
                        BPHTB Terhutang
                    </td>
                    <td rowspan="2" colspan="1">
                        Rp.
                    </td>
                    <td rowspan="2" colspan="1">
                        Tgl
                    </td>
                    <td rowspan="2" colspan="1">
                        Nama Notaris/PPATS
                    </td>
                </tr>
                <tr align="center">
                    <td rowspan="1" colspan="1">
                        Luas (m2)
                    </td>
                    <td rowspan="1" colspan="1">
                        NJOP (Rp/m2)
                    </td>
                    <td rowspan="1" colspan="1">
                        Luas (m2)
                    </td>
                    <td rowspan="1" colspan="1">
                        NJOP (Rp/m2)
                    </td>
                </tr>
                <?php
                $totalPembayaran = 0;
                $counter = 1;
                $t_totalspt = 0;
                $t_nilaipembayaranspt = 0;
                foreach ($this->data_Verifikasi as $k => $v) {
                    ?>
                    <tr>
                        <td align="center">
                            <?= $counter ?>
                        </td>
                        <td align="center">
                            <?php
                            $tanggal_bayar = explode('-', $v['t_tglverifikasispt']);
                            $tahun = $tanggal_bayar[0];
                            $bulan = $tanggal_bayar[1];
                            $tanggal = $tanggal_bayar[2];
                            ?>
                            <?= str_pad($v['t_kohirspt'], 4, '0', STR_PAD_LEFT) ?>
                        </td>
            <!--            <td>
                        <?= $v['t_nopbphtbsppt'] ?>
                        </td>-->
                        <td>
                            <?= strtoupper($v['t_namawppembeli']) ?> 
                        </td>
                        <td>
                            <?= $v['t_alamatwppembeli'] ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_nilaitransaksispt'], 0, ',', '.'); ?>
                        </td>
                        <td style="text-align: right">
                            <?= $v['t_luastanah'] ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_njoptanah'], 0, ',', '.'); ?>
                        </td>
                        <td style="text-align: right">
                            <?= $v['t_luasbangunan'] ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_njopbangunan'], 0, ',', '.'); ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_grandtotalnjop'], 0, ',', '.'); ?>
                        </td>
                        <td style="text-align: right">
                            <?php
                            $npop = $v['t_grandtotalnjop'] - $v['t_nilaipembayaranspt'];
                            ?>
                            <?= number_format($npop, 0, ',', '.'); ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_potonganspt'], 0, ',', '.') ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_totalspt'], 0, ',', '.'); ?>
                            <?php $t_totalspt += $v['t_totalspt']; ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_nilaipembayaranspt'], 0, ',', '.'); ?>
                            <?php $t_nilaipembayaranspt += $v['t_nilaipembayaranspt']; ?>
                        </td>
                        <td>
                            <?php
                            if (!empty($v['t_tanggalpembayaran'])) {
                                $tglbayar = date('d/m/Y', strtotime($v['t_tanggalpembayaran']));
                            } else {
                                $tglbayar = "";
                            }
                            ?>
                            <?= $tglbayar; ?>
                        </td>
                        <td>
                            <?= $v['s_namanotaris'] ?>
                        </td>
                        <td align="center">
                            <?= date('d/m/Y', strtotime($v['t_tglverifikasispt'])) ?>
                        </td>
                        <?php
                        $counter++;
                    }
                    ?>
                <tr>
                    <td colspan="8"></td>
                    <td colspan="5" style="text-align: right">
                        <div style="float: left;">
                            <b>BPHTB Terhutang : </b> 
                        </div>
                        <div style="float: right">
                            <b> <?= number_format($t_totalspt, 0, ',', '.'); ?></b>
                        </div>
                    </td>
                    <td colspan="3">
                        <div style="float: left;">
                            <b>Jumlah Pembayaran : </b> 
                        </div>
                        <div style="float: right">
                            <b> <?= number_format($t_nilaipembayaranspt, 0, ',', '.'); ?></b>
                        </div>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="8"></td>
                    <td colspan="8" style="text-align: right">
                        <div style="float: left;">
                            <b>Piutang BPHTB : </b> 
                        </div>
                        <div style="float: right">
                            <b> <?= number_format($t_totalspt - $t_nilaipembayaranspt, 0, ',', '.'); ?></b>
                        </div>
                    </td>
                    <td></td>
                </tr>
            </table>
        </div>
    </body>
    <footer></footer>
</html>
<style type="text/css" media="print">
    @media print {
        @page { 
            size: 210mm 297mm; /* landscape */
            margin-top: 5mm; 
        }
        body * {
            visibility: hidden;
        }
        .printarea, .printarea * {
            visibility: visible;
        }
        .printarea { /* aligning the printable area */
            position: absolute;
            margin-top: 0px;
            margin-left:0px; 
            margin-right:0px; 
        }
    }
</style>
<script type="text/javascript">
    $(function () {
        window.print();
        $("title").html("");
    });
</script>

