<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <a href="javascript:window.print()" class="btn btn-flat btn-primary"><span class="glyphicon glyphicon-print"></span> Print</a>
                                </div>
                            </div>
                        </div>
                        <div id="section-to-print">            
                            <h2 style="text-align: center">DAFTAR JENIS DOKUMEN TANAH BPHTB</h2>
                            <table width="100%" class="font_sembilan">
                                <tr style="text-align: center">
                                    <td style="width: 10%;">
                                        No.
                                    </td>
                                    <td>
                                        Nama Dokumen Tanah
                                    </td>
                                </tr>
                                <?php
                                $counter = 1;
                                foreach ($this->datadoktanah as $k => $v) {
                                    ?>
                                    <tr>
                                        <td style="text-align: center">
                                            <?= $counter ?>
                                        </td>
                                        <td>
                                            &nbsp;&nbsp;<?= $v['s_namadoktanah']; ?>
                                        </td>
                                    </tr>
                                    <?php
                                    $counter++;
                                }
                                ?>
                            </table>
                        </div>
                    </div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
</div><!-- /.row -->
</section><!-- /.content -->
</div><!-- /.content-wrapper -->
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    .font_sembilan {
        font-size: 9pt;
    }

    @media print {
        @page { 
            size: 210mm 297mm; /* landscape */
            margin-top: 5mm; 
        }
        body * {
            visibility: hidden;
        }
        #section-to-print, #section-to-print * {
            visibility: visible;
        }
        #section-to-print {
            position: absolute;
            left: 0;
            top: 0;
        }
    }
</style>
