<div class="content-wrapper" id="section-to-print">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <span style="font-size: 15px">SETTING TIPE DOKUMEN TANAH</span>
                                    <div class="pull-right">
                                        <a href="<?= $this->url() ?>/tambah" class="btn bg-purple btn-sm btn-flat"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;Tambah</a>
                                        <button class="btn btn-success btn-sm btn-flat" onclick="cetakdaftardoktanah();">
                                            <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Cetak Dok. Tanah
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 10px;margin-bottom: 10px">
                                <div class="col-sm-2">
                                    <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                        <option value="">Pilih Pencarian</option>
                                        <option value="s_namadoktanah">Nama Dok. Tanah</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                    <div class="input-group input-group-sm">
                                        <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                        <div class="input-group-btn combooperatorc">
                                            <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                                <option value="">Pilih</option>
                                                <option value="carisama">=</option>
                                                <option value="carilike">like</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3"></div>
                                <div class="col-sm-2">
                                    <span class="hiddene">
                                        <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                            <option value="">Pilih Sorting</option>
                                            <option value="s_namadoktanah">Nama Dok. Tanah</option>
                                        </select>
                                    </span>
                                </div>
                                <div class="col-sm-2">
                                    <span class="hiddene">
                                        <div class="form-inline">
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                                    Asc
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                                    Desc
                                                </label>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                            </div>
                            <div class="row">
                                <div style=" overflow: auto;">
                                    <div class="col-lg-12 col-sm12">
                                        <table class="table table-hover table-striped table-bordered" style="font-size: 12px">
                                            <thead>
                                                <tr class="bg-blue">  
                                                    <th class="text-center" style="width: 5%">
                                                        No.
                                                    </th>
                                                    <th class="text-center">
                                                        Nama Jenis Dokumen Tanah
                                                    </th>       
                                                    <th class="text-center" style="width: 15%">
                                                        #
                                                    </th>       
                                                </tr>
                                            </thead>
                                            <tbody id="body_grid">
                                            </tbody>
                                            <tfoot>              
                                                <tr>
                                                    <td colspan="5" class="text-center">
                                                        <div class="row">
                                                            <div class="col-sm-3 text-left">
                                                                <span class="hiddene">
                                                                    <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                                        <option value="10">10</option>
                                                                        <option value="20">20</option>
                                                                        <option value="30">30</option>
                                                                        <option value="40">40</option>
                                                                        <option value="50">50</option>
                                                                    </select>
                                                                </span>
                                                            </div>
                                                            <div class="col-sm-6" style="text-align: center">
                                                                <center>
                                                                    <div id="paginatore"></div>
                                                                    <input type="hidden" id="page" value="1">
                                                                </center>
                                                            </div>
                                                            <div class="col-sm-3 text-right">
                                                                <span class="hiddene">
                                                                    <p>
                                                                        <b><span id="awaldata"></span>-<span id="akhirdata"></span>/<span id="total_data"></span> Data</b>
                                                                    </p>  
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script type="text/javascript">
    $(function () {
        calldatagrid();
    });

    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapus/' + a);
            calldatagrid();
        }
        calldatagrid();
    }

    function cetakdaftardoktanah() {
        window.open('<?= $this->url() ?>/cetakdaftardoktanah')
    }
</script>
<style>
    @media print {
        body * {
            visibility: hidden;
        }
        #section-to-print, #section-to-print * {
            visibility: visible;
        }
        #section-to-print {
            position: absolute;
            left: 0;
            top: 0;
        }
    }
</style>
