<html moznomarginboxes mozdisallowselectionprint>
    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 8pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    

        </style>
    </head>    
    <body>
        <?php
        ini_set("max_execution_time", 5000);
        ini_set('memory_limit', '1024M');
        ?>
        <div class="printarea">
            <div>
                <div id='outerdiv'>
                    <div style='width: 10%; float: left;'>
                        <img src="http://<?= $_SERVER['HTTP_HOST']; ?>/<?= $this->basePath(); ?>/<?= $ar_pemda->s_logo ?>"style="height: 125px;">
                    </div>
                    <div style='width: 90%; float: right;'>
                        <p style="text-align: center; font-size: 14pt; font-weight: BOLD;">
                            PEMERINTAH <?= strtoupper($ar_pemda->s_namakabkot); ?>, <?= strtoupper($ar_pemda->s_namaprov); ?>
                        </p>
                        <p style="text-align: center; font-size: 18pt; font-weight: BOLD; line-height: 1px">
                            <?= strtoupper($ar_pemda->s_namainstansi); ?> (<?= strtoupper($ar_pemda->s_namasingkatinstansi); ?>)
                        </p>
                        <p style="text-align: center; font-size: 10pt; line-height: 5px">
                            <?= strtoupper($ar_pemda->s_alamatinstansi); ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>, <?= $ar_pemda->s_namaibukotakabkot ?> <?= $ar_pemda->s_kodepos ?>
                        </p>
                    </div>
                    <div style='clear:both;'></div>
                </div>
                <hr style="line-height: 1px; color: black">
                <h2 style="text-align: Right">DAFTAR DATA PENDAFTARAN</h2>
                <div id='outerdiv'>
                    <div style='width: 20%; float: left;'>
                        Tanggal Cetak
                    </div>
                    <div style='width: 80%; float: right;'>
                        : <?= $tgl_cetak ?>
                    </div>
                </div>
                <div id='outerdiv'>
                    <div style='width: 20%; float: left;'>
                        Tanggal Pendaftaran
                    </div>
                    <div style='width: 80%; float: right;'>
                        : <?= $tgl_pendaftaran1 ?> s/d <?= $tgl_pendaftaran2 ?>
                    </div>
                </div>
                <table width="100%" class="font_sembilan">
                    <tr style="text-align: center">
                        <td rowspan="2">
                            No.
                        </td>
                        <td rowspan="1" colspan="3">
                            Informasi Pihak Kedua (Penerima Hak)
                        </td>
                        <td rowspan="1" colspan="2">
                            Informasi Pihak Pertama (Pelepas Hak)
                        </td>
                        <td rowspan="1" colspan="3">
                            Informasi Objek Pajak
                        </td>
                        <td rowspan="1" colspan="6">
                            Informasi Transaksi
                        </td>
                    </tr>
                    <tr style="text-align: center">
                        <td rowspan="1" colspan="1">
                            NIK
                        </td>
                        <td rowspan="1" colspan="1">
                            Nama
                        </td>
                        <td rowspan="1" colspan="1">
                            Alamat
                        </td>
                        <td rowspan="1" colspan="1">
                            Nama
                        </td>
                        <td rowspan="1" colspan="1">
                            Alamat
                        </td>
                        <td rowspan="1" colspan="1">
                            NOP/Tahun SPPT
                        </td>
                        <td rowspan="1" colspan="1">
                            Nama SPPT
                        </td>
                        <td rowspan="1" colspan="1">
                            Letak Tanah / Bangunan
                        </td>
                        <td rowspan="1" colspan="1">
                            Jenis Transaksi
                        </td>
                        <td rowspan="1" colspan="1">
                            Nama Notaris/PPATS
                        </td>
                        <td rowspan="1" colspan="1">
                            Tgl Pendaftaran
                        </td>
                        <td rowspan="1" colspan="1">
                            Luas Tanah (Bumi)
                        </td>
                        <td rowspan="1" colspan="1">
                            Luas Bangunan
                        </td>
                        <td rowspan="1" colspan="1">
                            Harga Transaksi / Nilai Pasar
                        </td>
                    </tr>
                    <?php
                    $totalPembayaran = 0;
                    $counter = 1;
                    $jml_nilaitransaksi = 0;
                    foreach ($this->data_Verifikasi as $k => $v) {
                        ?>
                        <tr style="text-align: center">
                            <td>
                                <?= $counter ?>
                            </td>
                            <td>
                                <?= $v['t_nikwppembeli'] ?>
                            </td>
                            <td align="left">
                                <?= $v['t_namawppembeli'] ?>
                            </td>
                            <td align="left">
                                Kel. <?= $v['t_kelurahanwppembeli'] ?> Kec. <?= $v['t_kecamatanwppembeli'] ?> Kab/kota <?= $v['t_kabkotawppembeli'] ?>
                            </td>
                            <td align="left">
                                <?= $v['t_namawppenjual'] ?>
                            </td>
                            <td align="left">
                                Kel. <?= $v['t_kelurahanwppenjual'] ?> Kec.  <?= $v['t_kecamatanwppenjual'] ?> Kab/kota <?= $v['t_kabkotawppenjual'] ?>
                            </td>
                            <td>
                                <?= $v['t_nopbphtbsppt'] ?> - <?= $v['t_thnsppt'] ?>
                            </td>
                            <td align="left">
                                <?= $v['t_namasppt'] ?>
                            </td>
                            <td align="left">
                                <?= $v['t_alamatop'] ?>
                            </td>
                            <td>
                                <?= $v['s_namajenistransaksi'] ?>
                            </td>
                            <td align="left">
                                <?= $v['s_namanotaris'] ?>
                            </td>
                            <td>
                                <?= date('d/m/Y', strtotime($v['t_tglprosesspt'])) ?>
                            </td>
                            <td>
                                <?= $v['t_luastanah'] ?>
                            </td>
                            <td>
                                <?= $v['t_luasbangunan'] ?>
                            </td>
                            <td>
                                <?= number_format($v['t_nilaitransaksispt'], 0, ',', '.') ?>
                                <?php $jml_nilaitransaksi += $v['t_nilaitransaksispt']; ?>
                            </td>
                        <?php
                        $counter++;
                    }
                    ?>
                    <tr>
                        <td colspan="15" style="text-align: right;"><b>Jumlah :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?= number_format($jml_nilaitransaksi, 0, ',', '.') ?></b></td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
    <footer></footer>
</html>
<style type="text/css" media="print">
    @media print {
        @page { 
            size: auto;  
            margin-top: 5mm; 
        }
        body * {
            visibility: hidden;
        }
        .printarea, .printarea * {
            visibility: visible;
        }
        .printarea { /* aligning the printable area */
            position: absolute;
            margin-top: 0px;
            margin-left:0px; 
            margin-right:0px; 
        }
    }
</style>
<script type="text/javascript">
    $(function () {
        window.print();
//        $("#bodynya").addClass("sidebar-mini sidebar-collapse");
//        $("#bodynya").removeClass("layout-top-nav");
        $("title").html("");

//        $("#div_rekomendasi ol").attr("type", "a");
    });
</script>