<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">             
                                    <div class="col-sm-12">
                                        <span style="font-size: 15px">PENDAFTARAN</span>               
                                        <div class="pull-right">         
                                            <a href="<?= $this->url('pendataan_sspd') ?>/tambah" class="btn bg-purple btn-sm btn-flat">
                                                <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;Tambah
                                            </a>                                                             
                                            <div class="btn-group">
                                                <button data-toggle="dropdown" class="btn btn-success btn-flat btn-sm dropdown-toggle" type="button">
                                                    <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Cetak&nbsp;&nbsp;
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul role="menu" class="dropdown-menu pull-right bg-green">
                                                    <li><a href="#" style="color: black" onclick="openCetakPenelitian()">Cetak Permohonan Penelitian</a> </li>
                                                    <li><a href="#" style="color: black" onclick="openCetakBukti()">Cetak Bukti Penerimaan Surat/Berkas</a> </li>
                                                    <li><a href="<?= $this->url('pendataan_sspd') ?>/formcetakdatastatusberkas" style="color: black">Cetak Daftar Status Berkas</a></li>
                                                    <li><a href="<?= $this->url('pendataan_sspd') ?>/formcetakdatapendaftaran" style="color: black">Cetak Daftar Pendaftaran</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="row" style="margin-top: 10px;margin-bottom: 10px">
                                    <div class="col-sm-2">
                                        <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                            <option value="">Pilih Pencarian</option>
                                            <option value="t_kohirspt">No. Pendaftaran</option>
                                            <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                            <option value="t_periodespt">Periode Pajak</option>
                                            <option value="t_kohirketetapanspt">No. SSPD</option>
                                            <option value="t_nopbphtbsppt">NOP</option>
                                            <option value="t_namawppembeli">Nama WP</option>
                                            <option value="t_totalspt">Jumlah Pajak</option>
                                            <option value="t_dendaspt">Jumlah Denda</option>
                                            <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="input-group input-group-sm">
                                            <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                            <div class="input-group-btn combooperatorc">
                                                <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                                    <option value="">Pilih</option>
                                                    <option value="carisama">=</option>
                                                    <option value="carilike">like</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                                <option value="t_kohirspt">No. Pendaftaran</option>
                                                <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                                <option value="t_periodespt">Periode Pajak</option>
                                                <option value="t_kohirketetapanspt">No. SSPD</option>
                                                <option value="t_nopbphtbsppt">NOP</option>
                                                <option value="t_namawppembeli">Nama WP</option>
                                                <option value="t_totalspt">Jumlah Pajak</option>
                                                <option value="t_dendaspt">Jumlah Denda</option>
                                                <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                            </select>
                                        </span>
                                    </div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <div class="form-inline">
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                                        Asc
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                                        Desc
                                                    </label>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div style=" overflow: auto;">
                                        <div class="col-sm-12">
                                            <div class="unseen no-more-tables">
                                                <table class="table table-striped table-hover table-bordered" style="font-size: 12px">
                                                    <thead>
                                                        <tr class="bg-blue">  
                                                            <th class="text-center" style="width: 5%">
                                                                No. Daftar
                                                            </th>     
                                                            <th class="text-center" style="width: 5%">
                                                                No. SSPD
                                                            </th>     
                                                            <th class="text-center" style="width: 5%">
                                                                Tahun Pajak
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Tgl Proses
                                                            </th>     
                                                            <th class="text-center">
                                                                NOP
                                                            </th>     
                                                            <th class="text-center">
                                                                Nama WP
                                                            </th>     
                                                            <th class="text-center">
                                                                Pajak
                                                            </th>     
                                                            <th class="text-center">
                                                                Denda
                                                            </th>     
                                                            <th class="text-center" style="width: 10%">
                                                                Jenis Transaksi
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Status
                                                            </th>          
                                                            <th class="text-center" style="width: 5%">
                                                                Cetak SSPD
                                                            </th>           
                                                            <th class="text-center" style="width: 10%">
                                                                Pilihan
                                                            </th>    
                                                        </tr>
                                                    </thead>
                                                    <tbody id="body_grid">
                                                    </tbody>
                                                    <tfoot>              
                                                        <tr>
                                                            <td colspan="12" class="text-center">
                                                                <div class="row">
                                                                    <div class="col-sm-3 text-left">
                                                                        <span class="hiddene">
                                                                            <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                                                <option value="10">10</option>
                                                                                <option value="20">20</option>
                                                                                <option value="30">30</option>
                                                                                <option value="40">40</option>
                                                                                <option value="50">50</option>
                                                                            </select>
                                                                        </span>
                                                                    </div>
                                                                    <div class="col-sm-6" style="text-align: center">
                                                                        <center>
                                                                            <div id="paginatore"></div>
                                                                            <input type="hidden" id="page" value="1">
                                                                        </center>
                                                                    </div>
                                                                    <div class="col-sm-3 text-right">
                                                                        <span class="hiddene">
                                                                            <p>
                                                                                <b><span id="awaldata"></span>-<span id="akhirdata"></span>/<span id="total_data"></span> Data</b>
                                                                            </p>  
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </tfoot>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK SSPD</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <input type="text" id="periode_spt" value="<?= date('Y') ?>" style="width:20%">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <input type="text" id="tgl_cetak" value="<?= date('d-m-Y') ?>" style="width:35%">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor Pendaftaran
                        </td>
                        <td>
                            <input type="text" id="no_spt1" style="width: 20%">
                            s/d
                            <input type="text" id="no_spt2" style="width: 20%">
                        </td>
                    </tr>
                </table>
                <div align="right">
                    <button class="btn btn-success" onclick="cetaksspd();">Cetak</button> <button class="btn btn-success" onclick="tutup()">Tutup</button>
                </div>                
            </div>            
        </div>
    </div>
</div>

<div class="modal fade" id="cetakbuktipenerimaan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK BUKTI PENERIMAAN SURAT/BERKAS</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:30%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="periode_spt_bukti" value="<?= date('Y') ?>">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="tgl_cetak_bukti" id="tgl_cetak_bukti" value="<?= date('d-m-Y') ?>">
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor Pendaftaran
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="no_spt_bukti1">
                                </div>
                                <div class="col-sm-1">S/d</div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="no_spt_bukti2">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutupbukti()"><i class="glyphicon glyphicon-circle-arrow-left"></i> Tutup</button>
                    <button class="btn btn-danger btn-sm btn-flat" onclick="cetakbuktipenerimaan();"><i class="fa fa-fw fa-file-pdf-o"></i> CETAK PDF</button>
                </div>              
            </div>            
        </div>
    </div>
</div>

<div class="modal fade" id="myModalPenelitian" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK PERMOHONAN PENELITIAN</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:50%">
                            Tahun Pajak
                        </td>
                        <td>
                            <input type="text" class="form-control" id="periode_spt_penelitian" value="<?= date('Y') ?>">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <input type="text" class="form-control" id="tgl_cetak_penelitian" value="<?= date('d-m-Y') ?>">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor Pendaftaran
                        </td>
                        <td>
                            <input type="text" id="no_spt_penelitian" class="form-control">
                        </td>
                    </tr>
                </table>  
            </div>
            <div class="modal-footer">
                <div class="col-sm-12"> 
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutupCetakPenelitian()"><i class="glyphicon glyphicon-circle-arrow-left"></i> Tutup</button>
                    <button class="btn btn-danger btn-sm btn-flat" onclick="cetakpermohonanpenelitian();"><i class="fa fa-fw fa-file-pdf-o"></i> CETAK PDF</button>
                </div>              
            </div>            
        </div>
    </div>
</div>
<style type="text/css">
    @media only screen and (max-width: 800px) {
        .unseen table td:nth-child(2), 
        .unseen table td:nth-child(3), 
        .unseen table td:nth-child(4), 
        .unseen table td:nth-child(8), 
        .unseen table td:nth-child(9), 
        .unseen table td:nth-child(10),
        .unseen table td:nth-child(11), 
        .unseen table th:nth-child(11) {display: none;}
    }
</style>

<script>
    $(function () {
       calldatagrid();
    });

    $("#t_periodespt").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    $("#periode_spt_bukti").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#t_tglprosesspt").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#t_tglajbbaru").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_cetak").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_cetak_bukti").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#kb_tgl_cetak").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });
    jQuery("#tgl_cetaklapbulanan").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });
    jQuery("#tgl_cetaklapbulanan1").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });
    jQuery("#tgl_cetaklapbulanan2").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapus/' + a);
            calldatagrid();
        }
        calldatagrid();
    }


    function openCetak() {
        jQuery('#myModal').modal('show');
    }

    function tutup() {
        jQuery('#myModal').modal('hide');
        jQuery("#no_spt1,#no_spt2").val('');
    }

    function openCetakBukti() {
        jQuery('#cetakbuktipenerimaan').modal('show');
    }

    function tutupbukti() {
        jQuery('#cetakbuktipenerimaan').modal('hide');
        jQuery("#no_spt_bukti1,#no_spt_bukti2").val('');
    }

    function tutup2() {
        jQuery('#myModal2').modal('hide');
        jQuery("#kb_no_spt1,#kb_no_spt2").val('');
    }

    function openCetakLapBulanan() {
        jQuery('#myModalLapBulanan').modal('show');
    }

    function tutupLapBulanan() {
        jQuery('#myModalLapBulanan').modal('hide');
        jQuery("#no_spt1,#no_spt2").val('');
    }

    function cetaksspd() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetaksspdbphtb?no_spt1=' + $("#no_spt1").val() + "&no_spt2=" + $("#no_spt2").val() + "&periode_spt=" + $("#periode_spt").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetak").val())
    }

    function cetakbuktipenerimaan() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetakbuktipenerimaan?no_spt1=' + $("#no_spt_bukti1").val() + "&no_spt2=" + $("#no_spt_bukti2").val() + "&periode_spt=" + $("#periode_spt_bukti").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetak_bukti").val())
    }

//    function cetakLapBulanan() {
//        window.open('<?= $this->url('cetak_laporan') ?>/cetaklapbulananbphtb?periode_spt=' + $("#periode_spt").val() + "&tgl_cetaklapbulanan=" + $("#tgl_cetaklapbulanan").val() + "&tgl_cetaklapbulanan1=" + $("#tgl_cetaklapbulanan1").val() + "&tgl_cetaklapbulanan2=" + $("#tgl_cetaklapbulanan2").val())
//    }

//  =====================================================
//  Cetak Permohonan Penelitian
    function openCetakPenelitian() {
        jQuery('#myModalPenelitian').modal('show');
    }

    function tutupCetakPenelitian() {
        jQuery('#myModalPenelitian').modal('hide');
    }

    $("#periode_spt_penelitian").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetak_penelitian").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function cetakpermohonanpenelitian() {
        window.open('<?= $this->url() ?>/cetakpermohonanpenelitian?periode_spt_penelitian=' + $("#periode_spt_penelitian").val() + "&tgl_cetak_penelitian=" + $("#tgl_cetak_penelitian").val() + "&no_spt_penelitian=" + $("#no_spt_penelitian").val())
    }

//    ===================================================

</script>