<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-warning">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <u style="font-size: 14px; color: blue"><strong>Informasi Pihak Kedua(Penerima Hak)</strong></u>
                                        <div class="pull-right">
                                            <?php
                                            if (@$role_id == 6) { ?>
                                                
                                            <?php } else {
                                                ?>
                                                <a href="<?= $this->url() ?>" class="btn btn-primary btn-flat btn-sm">Kembali</a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Tgl Pendaftaran <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-3">
                                        <?= $datasspd->t_tglprosesspt ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NIK <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_nikwppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        NPWP <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_npwpwppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Nama <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_namawppembeli ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Alamat <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_alamatwppembeli ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        RT/RW <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_rtwppembeli ?> / <?= $datasspd->t_rwwppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kelurahan / Desa  <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kelurahanwppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kecamatan <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kecamatanwppembeli ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Kabupaten / Kota <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kabkotawppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kode Pos <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kodeposwppembeli ?>
                                    </div>
                                    <div class="col-sm-2">
                                        No Telp <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_telponwppembeli ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-warning">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <u style="font-size: 14px; color: blue"><strong>Informasi Pihak Pertama(Pelepas Hak)</strong></u>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NIK <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_nikwppenjual ?>
                                    </div>
                                    <div class="col-sm-2">
                                        NPWP <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_npwpwppenjual ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Nama <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_namawppenjual ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Alamat <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-9">
                                        <?= $datasspd->t_alamatwppenjual ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        RT/RW <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_rtwppenjual ?> / <?= $datasspd->t_rwwppenjual ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kelurahan / Desa <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kelurahanwppenjual ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kecamatan <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kecamatanwppenjual ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Kabupaten / Kota <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kabkotawppenjual ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kode Pos <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kodeposwppenjual ?>
                                    </div>
                                    <div class="col-sm-2">
                                        No Telp <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_telponwppenjual ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-warning">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <u style="font-size: 14px; color: blue"><strong>INFORMASI OBJEK PAJAK</strong></u>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NOP / Thn SPPT <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-6" style="font-size: 12px">
                                        <?= $datasspd->t_nopbphtbsppt ?> / <?= $datasspd->t_thnsppt ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Nama SPPT <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_namasppt ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Letak <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_alamatop ?>
                                    </div>
                                    <div class="col-sm-2">
                                        RT/RW <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_rtop ?> / <?= $datasspd->t_rwop ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Kelurahan/Desa <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kelurahanop ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kecamatan <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kecamatanop ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kabupaten/Kota <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_kabkotawppembeli ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Jenis Transaksi <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->s_namajenistransaksi ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Jenis Dokumen <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">

                                    </div>
                                    <div class="col-sm-2">
                                        No. Dok Tanah <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_nosertifikathaktanah ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Tgl AJB Lama <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->t_tglajb ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Kepemilikan <span class="pull-right">:</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <?= $datasspd->s_namahaktanah ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-warning">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <u style="font-size: 14px; color: blue"><strong>INFORMASI TRANSAKSI</strong></u>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Luas Tanah/Bumi
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= $datasspd->t_luastanah ?> m<sup>2</sup>
                                    </div>
                                    <div class="col-sm-2">
                                        NJOP/m<sup>2</sup> Tanah/Bumi
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_njoptanah, 0, ',', '.') ?>
                                    </div>
                                    <div class="col-sm-2">
                                        NJOP Tanah/Bumi
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_totalnjoptanah, 0, ',', '.') ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Luas Bangunan
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= $datasspd->t_luasbangunan ?> m<sup>2</sup>
                                    </div>
                                    <div class="col-sm-2">
                                        NJOP/m<sup>2</sup> Bangunan
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_njopbangunan, 0, ',', '.') ?>
                                    </div>
                                    <div class="col-sm-2">
                                        NJOP Bangunan
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_totalnjopbangunan, 0, ',', '.') ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NJOP PBB
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_grandtotalnjop, 0, ',', '.') ?>
                                    </div>
                                    <div class="col-sm-2">
                                        Harga Transaksi
                                    </div>
                                    <div class="col-sm-2">
                                        : <?= number_format($datasspd->t_nilaitransaksispt, 0, ',', '.') ?>
                                    </div>
                                </div>
                                <?php
                                if ($datasspd->t_grandtotalnjop > $datasspd->t_nilaitransaksispt) {
                                    $npop = $datasspd->t_grandtotalnjop;
                                } else {
                                    $npop = $datasspd->t_nilaitransaksispt;
                                }
                                $npopkp = $npop - $datasspd->t_potonganspt;
                                if ($npopkp > 0) {
                                    $npopkp = $npopkp;
                                } else {
                                    $npopkp = 0;
                                }
                                ?>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NPOP
                                    </div>
                                    <div class="col-sm-10">
                                        : <?= number_format($npop, 0, ',', '.') ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NPOPTKP
                                    </div>
                                    <div class="col-sm-2">
                                        : <u><?= number_format($datasspd->t_potonganspt, 0, ',', '.') ?>&nbsp;&nbsp;&nbsp;&nbsp;-</u>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        NPOPTKP
                                    </div>
                                    <div class="col-sm-10">
                                        : <?= number_format($npopkp, 0, ',', '.') ?>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Tarif (%)
                                    </div>
                                    <div class="col-sm-10">
                                        : <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5%&nbsp;&nbsp;&nbsp;&nbsp;x</u>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="col-sm-2">
                                        Pajak Terhutang
                                    </div>
                                    <div class="col-sm-2">
                                        : <b style="color: red; font-size: 17px;"><?= number_format($datasspd->t_totalspt, 0, ',', '.') ?></b>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>