<?=$this->menu;?>
<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title"><span style="font-size: 10pt">Navigasi Pembayaran</span></h3></div>
        <div class="panel-body">
            <?= $this->side_menu ?>
        </div>        
    </div>    
</div>
<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading"><h3 class="panel-title"><span style="font-size: 10pt">Pembayaran</span></h3></div>
        <div class="panel-body">
        </div>        
    </div>    
</div>
    