<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <span style="font-size: 15px">PEMBAYARAN</span>
                                        <div class="pull-right">
                                            <a href="<?= $this->url('pembayaran_sptbphtb') ?>/tambah" class="btn bg-purple btn-sm btn-flat"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;Pembayaran</a> 
                                            <a href="#" class="btn btn-success btn-sm btn-flat" onclick="openCetakPencatatanSetoran()"><span class="glyphicon glyphicon-print"></span> &nbsp;Cetak Daftar Pembayaran</a>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="row" style="margin-top: 10px;margin-bottom: 10px">
                                    <div class="col-sm-2">
                                        <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                            <option value="">Pilih Pencarian</option>
                                            <option value="t_kodebayarbanksppt">Kode Bayar</option>
                                            <option value="t_kohirspt">No. Pendaftaran</option>
                                            <option value="t_tanggalpembayaran">Tgl. Pembayaran</option>
                                            <option value="t_periodespt">Periode Pajak</option>
                                            <option value="t_kohirketetapanspt">No. SSPD</option>
                                            <option value="t_nopbphtbsppt">NOP</option>
                                            <option value="t_namawppembeli">Nama WP</option>
                                            <option value="t_totalspt">Jumlah Pajak</option>
                                            <option value="t_dendaspt">Jumlah Denda</option>
                                            <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="input-group input-group-sm">
                                            <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                            <div class="input-group-btn combooperatorc">
                                                <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                                    <option value="">Pilih</option>
                                                    <option value="carisama">=</option>
                                                    <option value="carilike">like</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                                <option value="">Pilih Sorting</option>
                                                <option value="t_tanggalpembayaran">Tgl. Pembayaran</option>
                                                <option value="t_kodebayarbanksppt">Kode Bayar</option>
                                                <option value="t_kohirspt">No. Pendaftaran</option>
                                                <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                                <option value="t_periodespt">Periode Pajak</option>
                                                <option value="t_kohirketetapanspt">No. SSPD</option>
                                                <option value="t_nopbphtbsppt">NOP</option>
                                                <option value="t_namawppembeli">Nama WP</option>
                                                <option value="t_totalspt">Jumlah Pajak</option>
                                                <option value="t_dendaspt">Jumlah Denda</option>
                                                <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                            </select>
                                        </span>
                                    </div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <div class="form-inline">
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                                        Asc
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                                        Desc
                                                    </label>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div style=" overflow: auto;">
                                        <div class="col-lg-12 col-sm12">
                                            <div class="unseen no-more-tables">
                                                <table class="table table-striped table-hover table-bordered" style="font-size: 12px">
                                                    <thead>
                                                        <tr class="bg-blue">  
                                                            <th class="text-center" style="width: 5%">
                                                                No. Daftar
                                                            </th>           
                                                            <th class="text-center" style="width: 5%">
                                                                NOP
                                                            </th>          
                                                            <th class="text-center" style="width: 5%">
                                                                Tahun Bayar
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Tgl Pembayaran
                                                            </th>     
                                                            <th class="text-center">
                                                                Nama WP
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Kode Bayar
                                                            </th>     
                                                            <th class="text-center">
                                                                Jumlah Pembayaran
                                                            </th>     
                                                            <th class="text-center">
                                                                Cetak
                                                            </th>           
                                                            <th class="text-center">
                                                                Pilihan
                                                            </th>  
                                                        </tr>
                                                    </thead>
                                                    <tbody id="body_grid">
                                                    </tbody>
                                                    <tfoot>              
                                                        <tr>
                                                            <td colspan="9" class="text-center">
                                                                <div class="row">
                                                                    <div class="col-sm-3 text-left">
                                                                        <span class="hiddene">
                                                                            <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                                                <option value="10">10</option>
                                                                                <option value="20">20</option>
                                                                                <option value="30">30</option>
                                                                                <option value="40">40</option>
                                                                                <option value="50">50</option>
                                                                            </select>
                                                                        </span>
                                                                    </div>
                                                                    <div class="col-sm-6" style="text-align: center">
                                                                        <center>
                                                                            <div id="paginatore"></div>
                                                                            <input type="hidden" id="page" value="1">
                                                                        </center>
                                                                    </div>
                                                                    <div class="col-sm-3 text-right">
                                                                        <span class="hiddene">
                                                                            <p>
                                                                                <b><span id="awaldata"></span>-<span id="akhirdata"></span>/<span id="total_data"></span> Data</b>
                                                                            </p>                  
                                                                        </span>                  
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </tfoot>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<div class="modal fade" id="myModalPencatatanSetoran" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK DAFTAR PEMBAYARAN</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-5">
                                    <input type="text" id="periode_spt" value="<?= date('Y') ?>" class="form-control">
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-5">
                                    <input type="text" id="tgl_cetakpencatatan" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Pembayaran
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-5">
                                    <input type="text" id="tgl_pembayaran1" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                                <div class="col-sm-1">s/d</div>
                                <div class="col-sm-5">
                                    <input type="text" id="tgl_pembayaran2" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div> 
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutupPencatatanSetoran()"><i class="glyphicon glyphicon-circle-arrow-left"></i> Tutup</button>
                    <button class="btn btn-success btn-sm btn-flat" onclick="cetakPencatatanSetoran();">
                        <span class="glyphicon glyphicon-print"></span> Cetak
                    </button>
                </div>
            </div>            
        </div>
    </div>
</div>
<style type="text/css">
    @media only screen and (max-width: 800px) {
        .unseen table td:nth-child(2), 
        .unseen table td:nth-child(3), 
        .unseen table td:nth-child(6), 
        .unseen table td:nth-child(7), 
        .unseen table td:nth-child(9), 
        .unseen table th:nth-child(9) {display: none;}
        .hiddene {display: none;}
    }
</style>
<script type="text/javascript">
    $(function () {
        calldatagrid();
    });

    $("#t_periodepembayaran").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#t_tanggalpembayaran").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_cetak").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function hapus(a) { // a=id_pembayaran, b=status verifikasi, c= status validasi
        var aa = confirm('Hapus data ini?');
        $.post('<?= $this->url() ?>/hapus', {t_idpembayaranspt: a}, function (data) {
            calldatagrid();
        });
        calldatagrid();
    }

    function updatepemeriksaan(a) {
        $.post('<?= $this->url() ?>/updatepemeriksaan', {p_idpemeriksaan: a}, function (data) {

        });
    }

//  ======================================================
//  Cetak Daftar Pembayaran
    $("#periode_spt").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetakpencatatan").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_pembayaran1").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_pembayaran2").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function openCetakPencatatanSetoran() {
        jQuery('#myModalPencatatanSetoran').modal('show');
    }

    function tutupPencatatanSetoran() {
        jQuery('#myModalPencatatanSetoran').modal('hide');
        jQuery("#no_spt1,#no_spt2").val('');
    }

    function cetakPencatatanSetoran() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetakpencatatansetoranbphtb?periode_spt=' + $("#periode_spt").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetakpencatatan").val() + "&tgl_pembayaran1=" + $("#tgl_pembayaran1").val() + "&tgl_pembayaran2=" + $("#tgl_pembayaran2").val())
    }

//  =======================================================

</script>
