<?php
$data_pemda = $this->data_pemda;
?>
<table>
    <tr>
        <td width="100px">
            <?php $gambar = "/var/www/html" . $this->basePath() . "/" . $data_pemda->s_logo; ?>                                                                        
            <img width="50" title="LOGO <?= $data_pemda->s_namakabkot; ?>" align="left" src="<?=$gambar?>" />
        </td>
        <td style="text-align: center;">
            <b>PEMERINTAH <?= strtoupper($data_pemda->s_namakabkot); ?>, <?= strtoupper($data_pemda->s_namaprov); ?></b><br>
            <b style="font-size: 15px"><?= strtoupper($data_pemda->s_namainstansi); ?> (<?= strtoupper($data_pemda->s_namasingkatinstansi); ?>)</b><br>
            <b style="font-size: 12px"><?= strtoupper($data_pemda->s_alamatinstansi); ?> Telp/Fax <?= $data_pemda->s_notelinstansi ?>, <?= $data_pemda->s_namaibukotakabkot ?> <?= $data_pemda->s_kodepos ?></b>
        </td>
    </tr>
</table>
<hr>
<table width="100%" style="border-spacing: 0" class="font_sembilan">
    <tr style="text-align: center;" class="font_delapan">
        <td colspan="7">
            <br>
            REGISTER PEMBAYARAN BPHTB
        </td>
    </tr>
    <tr style="text-align: center;" class="font_delapan">
        <td colspan="7">
            TAHUN ANGGARAN <?= $periode_spt ?>
            <br><br>
        </td>
    </tr>
    <tr style="text-align: left;" class="font_tujuh">
        <td colspan="7">
            Tanggal Cetak : <?= $tgl_cetak ?>
        </td>
    </tr>
    <tr style="text-align: center">
        <td class="border_atas border_bawah border_kanan border_kiri" style="width: 5%;">
            No.
        </td>
        <td class="border_atas border_bawah border_kanan" style="width: 13%;">
            Nomor Dokumen
        </td>
        <td class="border_atas border_bawah border_kanan" style="width: 11%;">
            Tgl. Setoran
        </td>
        <td class="border_atas border_bawah border_kanan" style="width: 11%;">
            Kode Rekening
        </td>
        <td class="border_atas border_bawah border_kanan">
            Uraian
        </td>
        <td class="border_atas border_bawah border_kanan">
            Penyetor
        </td>
        <td class="border_atas border_bawah border_kanan">
            Jumlah Setoran
        </td>
    </tr>
    <?php
    $totalPembayaran = 0;
    $counter = 1;
    foreach ($this->data_pencatatanSetoran as $k => $v) {
        ?>
        <tr>
            <td class="border_bawah border_kanan border_kiri" style="text-align: center">
                <?= $counter ?>
            </td>
            <td class="border_bawah border_kanan" style="text-align: center">
                <?php
                $tanggal_bayar = explode('-', $v['t_tanggalpembayaran']);
                $tahun = $tanggal_bayar[0];
                $bulan = $tanggal_bayar[1];
                $tanggal = $tanggal_bayar[2];
                ?>
                <?= $tanggal . "." . $bulan . "." . $tahun . "." . str_pad($v['t_kohirspt'], 4, '0', STR_PAD_LEFT) ?>
            </td>
            <td class="border_bawah border_kanan" style="text-align: center">
                <?= date('d-m-Y', strtotime($v['t_tanggalpembayaran'])) ?>
            </td>
            <td class="border_bawah border_kanan" style="text-align: center">
                4.1.1.1.3.01.01
            </td>
            <td class="border_bawah border_kanan">
                <?= $v['s_namajenistransaksi'] ?>
            </td>
            <td class="border_bawah border_kanan">
                <?= strtoupper($v['t_namawppembeli']) ?> 
            </td>
            <td class="border_bawah border_kanan" style="text-align: right">
                <?= number_format($v['t_nilaipembayaranspt'], 2, ',', '.') ?>
            </td>
        </tr>
        <?php
        $totalPembayaran += $v['t_nilaipembayaranspt'];
        $counter++;
    }
    ?>
    <tr>
        <td colspan="6" class="border_kiri border_bawah border_kanan"  style="text-align: center">
            Jumlah
        </td>
        <td class="border_bawah border_kanan"  style="text-align: right">
            Rp. <?= number_format($totalPembayaran, 2, ',', '.') ?>
        </td>
    </tr>
</table>

<style type="text/css">

    .border_atas {
        border-top: 1px black solid;
    }

    .border_kiri {
        border-left: 1px black solid;
    }

    .border_kanan {
        border-right: 1px black solid;
    }

    .border_bawah {
        border-bottom: 1px black solid;
    }

    .font_besar {
        font-size: 12pt;
    }

    .font_kecil {
        font-size: 10pt;
    }

    .font_lima {
        font-size: 7pt;
    }

    .font_tujuh {
        font-size: 7pt;
    }  

    .font_delapan {
        font-size: 8pt;
    }    

    .font_sembilan {
        font-size: 9pt;
    }    


    @page {
        margin-top: 1.5em;  
        margin-left: 3.8em;          
    }
</style>