<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">        
        <?php if ($this->nilai == null || $this->nilai == 1 || $this->nilai == 6) {
            ?>
            <?php echo $this->headTitle('E-BPHTB KABUPATEN BANDUNG BARAT')->setSeparator(' - ')->setAutoEscape(false) ?>

            <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

            <!-- Le styles -->
            <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/upload/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/daterangepicker/daterangepicker-bs3.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/datepicker/datepicker3.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/select2/select2.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/morris/morris.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/plugins/iCheck/flat/blue.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/dist/css/skins/_all-skins.min.css')
                    ->prependStylesheet($this->basePath() . '/public/adminlte/dist/css/AdminLTE.min.css')
                    ->prependStylesheet($this->basePath('public/adminlte/plugins/ionicons/css/ionicons.min.css'))
                    ->prependStylesheet($this->basePath('public/adminlte/plugins/font-awesome/css/font-awesome.min.css'))
                    ->prependStylesheet($this->basePath() . '/public/adminlte/bootstrap/css/bootstrap.min.css')
            ?>

            <!-- Scripts -->
            <?php
            echo $this->headScript()
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/select2/select2.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/input-mask/jquery.inputmask.extensions.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/input-mask/jquery.inputmask.js')
                    ->prependFile($this->basePath() . '/public/adminlte/dist/js/app.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/fastclick/fastclick.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/slimScroll/jquery.slimscroll.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/datepicker/bootstrap-datepicker.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/daterangepicker/daterangepicker.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/knob/jquery.knob.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/sparkline/jquery.sparkline.min.js')
                    ->prependFile($this->basePath() . '/public/adminlte/plugins/morris/morris.min.js')
                    ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
                    ->prependFile($this->basePath() . '/public/js/jquery.min.js')
                    ->prependFile($this->basePath() . '/public/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                    ->prependFile($this->basePath() . '/public/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ?>
            <?php
            if ($this->nilai == null) {
                $classbody = 'hold-transition skin-blue sidebar-mini';
                $idbody = '';
            } elseif ($this->nilai == 1) {
                $classbody = 'hold-transition login-page';
                $idbody = '';
            } elseif ($this->nilai == 6) {
                $classbody = 'hold-transition skin-blue sidebar-mini sidebar-collapse';
                $idbody = '';
            }
        } elseif ($this->nilai == 2) {
            echo $this->headTitle('E-BPHTB')->setSeparator(' - ')->setAutoEscape(false);
            echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/upload/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/public/creative/css/creative.css')
                    ->prependStylesheet($this->basePath() . '/public/creative/css/animate.min.css')
                    ->prependStylesheet($this->basePath() . '/public/creative/font-awesome/css/font-awesome.min.css')
                    ->prependStylesheet($this->basePath() . '/public/creative/css/cyrillic.css')
                    ->prependStylesheet($this->basePath() . '/public/creative/css/cyrillic2.css')
                    ->prependStylesheet($this->basePath() . '/public/creative/css/bootstrap.min.css');
            ?>
            <?php
            $classbody = '';
            $idbody = 'page-top';
        }
        ?>
<!--<script type = "text/javascript" > jQuery . noConflict()</script>-->
<!--<script type="text/javascript" src="<?php /* $this->basePath() . '/public/locales/bootstrap-datepicker.id.min.js'; */ ?>"></script>--> 
    </head>
    <body class="<?= $classbody ?>" id="<?= $idbody ?>"> 
        <div class="loader"></div>
        <?php if ($this->nilai == null || $this->nilai == 6) {
            ?>
            <div id="wrapper" class="wrapper">
                <?= $this->partial('menu.phtml'); ?>
                <?= $this->partial('side_menu.phtml'); ?>
                <?= $this->content; ?>
                <?= $this->partial('footer.phtml'); ?>  
                <?= $this->partial('side_right.phtml'); ?>  
            </div>       
            <?php
        } elseif ($this->nilai == 1 || $this->nilai == 2) {
            ?> 
            <?= $this->content; ?>
        <?php } ?>
    </body>
</html>
<?php $gambar = "http://" . $_SERVER['HTTP_HOST'] . "/" . $this->basePath() . "/public/upload/loading1.gif"; ?>
<style>
    .loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background: url(<?= $gambar ?>) 50% 50% no-repeat rgb(249,249,249);
    }

    .combooperatorc select {
        border: 0 !important;  /*Removes border*/
        -webkit-appearance: none;  /*Removes default chrome and safari style*/
        -moz-appearance: none; /* Removes Default Firefox style*/
        appearance:none;
        /*background: #E08E0B url(img/select-arrow.png) no-repeat 90% center;*/
        background: #E08E0B no-repeat 90% center;
        text-indent: 0.01px; /* Removes default arrow from firefox*/
        color: #FFF;
    }	

    @media only screen and (max-width: 800px) {
        /* Force table to not be like tables anymore */
        .no-more-tables table, 
        .no-more-tables thead, 
        .no-more-tables tbody, 
        .no-more-tables tfoot, 
        .no-more-tables th, 
        .no-more-tables td, 
        .no-more-tables tr { 
            display: block; 
        }

        .hiddene {display: none;}

        /* Hide table headers (but not display: none;, for accessibility) */
        .no-more-tables thead tr { 
            position: absolute;
            top: -9999px;
            left: -9999px;
        }

        .no-more-tables tr { border: 1px solid #ccc; }

        .no-more-tables td { 
            /* Behave  like a "row" */
            border: none;
            border-bottom: 1px solid #eee; 
            position: relative;
            padding-left: 50%; 
            white-space: normal;
            text-align:left;
        }

        .no-more-tables td:before { 
            /* Now like a table header */
            position: absolute;
            /* Top/left values mimic padding */
            top: 6px;
            left: 6px;
            width: 45%; 
            padding-right: 10px; 
            white-space: nowrap;
            text-align:left;
            font-weight: bold;
        }

        /*
        Label the data
        */
        .no-more-tables td:before { content: attr(data-title); }
    }
</style>
<script type="text/javascript">
    jQuery(window).load(function () {
        $(".loader").fadeOut("slow");
    });
    jQuery('body').on('keydown', 'input, select, textarea', function (e) {
        var self = $(this)
                , form = self.parents('form:eq(0)')
                , focusable
                , next
                ;
        if (e.keyCode == 13) {
            focusable = form.find('input,a,select,button,textarea').filter(':visible');
            next = focusable.eq(focusable.index(this) + 1);
            if (next.length) {
                next.focus();
            } else {
                form.submit();
            }
            return false;
        }
    });
    jQuery(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
    function unformatCurrency(num)
    {
        if (num != "" || num != "undefined")
            num = num.replace(/\$|\,00/g, '').replace(/\$|\./g, '');
        if (num == 0)
            num = '';
        return num;
    }
    function unformatNumber(num)
    {
        if (num != "" || num != "undefined")
            num = num.replace(/\$|\.00/g, '').replace(/\$|\./g, '');
        if (num == 0)
            num = '';
        return num;
    }

    function formatCurrency(num)
    {
        if (num != "" || num != "undefined")
        {
            //                    num = num.replace(/\$|\,00/g, '').replace(/\$|\./g, '');
            num = num.replace(/\$|\,00/g, '').replace(/\$|\./g, '');
            sign = (num == (num = Math.abs(num)));
            num = Math.floor(num * 100 + 0.50000000001);
            cents = num % 100;
            num = Math.floor(num / 100).toString();
            if (cents < 10)
                cents = "0" + cents;
            for (var i = 0; i < Math.floor((num.length - (1 + i)) / 3); i++)
                num = num.substring(0, num.length - (4 * i + 3)) + '.' + num.substring(num.length - (4 * i + 3));
            return (((sign) ? '' : '-') + num);
            //                    return (((sign) ? '' : '-') + num + ',' + cents);
            /*			}*/
        }
    }

    //Membuat Format Mata Uang
    function currencyFormatDE(num) {
        return num
                .toFixed(0) // always two decimal digits
                .replace(".", ",") // replace decimal point character with ,
                .replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.") // use . as a separator
    }

    function numbersonly(myfield, e, dec)
    {
        var key;
        var keychar;

        if (window.event)
            key = window.event.keyCode;
        else if (e)
            key = e.which;
        else
            return true;
        keychar = String.fromCharCode(key);
        // control keys
        if ((key == null) || (key == 0) || (key == 8) ||
                (key == 9) || (key == 13) || (key == 27))
            return true;

        // numbers
        else if ((("0123456789").indexOf(keychar) > -1))
            return true;

        // decimal point jump
        else if (dec && (keychar == "."))
        {
            myfield.form.elements[dec].focus();
            return false;
        }
        else
            return false;
    }

    function calldatagrid(direction) {
        if ($("#combocari").val().length == 0)
            par1 = undefined;
        else
            par1 = $("#combocari").val()
        if ($("#kolomcari").val().length == 0)
            par2 = undefined;
        else
            par2 = $("#kolomcari").val()
        if ($("#combosorting").val().length == 0)
            par3 = undefined;
        else
            par3 = $("#combosorting").val()
        if (document.getElementById("sortasc").checked)
            par4 = $("#sortasc").val()
        else
            par4 = undefined;
        if (document.getElementById("sortdesc").checked)
            par5 = $("#sortdesc").val()
        else
            par5 = undefined;
        if ($("#combooperator").val().length == 0)
            par6 = undefined;
        else
            par6 = $("#combooperator").val()
        datagrid($("#page").val(), $("#rows").val(), direction, par1, par2, par3, par4, par5, par6);
    }

    function datagrid(page, row, direction, par1, par2, par3, par4, par5, par6) {
        $.get('<?= $this->url() ?>/dataGrid/' + page + '/' + row + '/' + direction + '/' + par1 + '/' + par2 + '/' + par3 + '/' + par4 + '/' + par5 + '/' + par6, function (data) {
            var aa = JSON.parse(data)
            $("#body_grid").html(aa.grid);
            $("#rows").val(aa.rows);
            $("#page").val(aa.page);
            $("#total_data").html(": " + aa.count);
            $("#total_halaman").html(": " + aa.total_halaman);
            $("#paginatore").html(aa.paginatore);
            $("#awaldata").html(aa.awaldata);
            $("#akhirdata").html(aa.akhirdata);
        });
    }
</script>