<html moznomarginboxes mozdisallowselectionprint>
    <head>
        <style type="text/css">
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }

            .font_empatbelas {
                font-size: 14pt;
            }    
        </style>
    </head>
    <body>
        <?php
        ini_set("max_execution_time", 5000);
        ini_set('memory_limit', '1024M');
        ?>
        <div class="printarea">            
            <h2 style="text-align: center">DAFTAR HARGA ACUAN BPHTB</h2>
            <table width="100%" class="font_empatbelas">
                <tr style="text-align: center">
                    <td style="width: 5%;">
                        No.
                    </td>
                    <td>
                        Kode Provinsi
                    </td>
                    <td>
                        Kode Kabupaten
                    </td>
                    <td>
                        Kode Kecamatan
                    </td>
                    <td>
                        Kode Kelurahan
                    </td>
                    <td>
                        Kode Blok
                    </td>
                    <td>
                        Harga/m<sup>2</sup>
                    </td>
                </tr>
                <?php
                $counter = 1;
                foreach ($this->dataacuan as $k => $v) {
                    ?>
                    <tr>
                        <td style="text-align: center">
                            <?= $counter ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kd_propinsi']; ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kd_dati2']; ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kd_kecamatan']; ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kd_kelurahan']; ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kd_blok']; ?>
                        </td>
                        <td align="right">
                            <?= number_format($v['s_permetertanah'], 0, ",", "."); ?>
                        </td>
                    </tr>
                    <?php
                    $counter++;
                }
                ?>
            </table>
        </div>
    </body>
</html>
<style type="text/css" media="print">
    @media print {
        @page { 
            size: 210mm 297mm; /* landscape */
            margin-top: 5mm; 
        }
        body * {
            visibility: hidden;
        }
        .printarea, .printarea * {
            visibility: visible;
        }
        .printarea { /* aligning the printable area */
            position: absolute;
            margin-top: 0px;
            margin-left:0px; 
            margin-right:0px; 
        }
    }
</style>
<script type="text/javascript">
    $(function () {
        window.print();
        $("title").html("");
    });
</script>
