<html>
    <head>
        <style type="text/css">
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }

            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 8pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    
        </style>
    </head>
    <body>
        <div class="printarea">            
            <h2 style="text-align: center">DAFTAR TARIF NPOPTKP BPHTB</h2>
            <table width="100%" class="font_sembilan">
                <tr style="text-align: center">
                    <td style="width: 5%;">
                        No.
                    </td>
                    <td style="width: 13%;">
                        Kode Transaksi
                    </td>
                    <td>
                        Nama Transaksi
                    </td>
                    <td>
                        Tahun AJB Berlaku
                    </td>
                    <td>
                        Tahun AJB Berakhir
                    </td>
                    <td>
                        Tarif NPOPTKP
                    </td>
                </tr>
                <?php
                $counter = 1;
                foreach ($this->datatarifnpoptkp as $k => $v) {
                    ?>
                    <tr>
                        <td style="text-align: center">
                            <?= $counter ?>
                        </td>
                        <td align="center">
                            <?= $v['s_kodejenistransaksi'] ?>
                        </td>
                        <td>
                            <?= $v['s_namajenistransaksi']; ?>
                        </td>
                        <td>
                            <?= $v['s_tarifnpotkptahunajb1']; ?>
                        </td>
                        <td>
                            <?= $v['s_tarifnpotkptahunajb2']; ?>
                        </td>
                        <td align="right" style="width: 20%">
                            <?= number_format($v['s_tarifnpotkp'], 0, ',', '.'); ?>
                        </td>
                    </tr>
                    <?php
                    $counter++;
                }
                ?>
            </table>
        </div>
    </body>
</html>

