<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->prepare();
?>
<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Validasi SSPD BPHTB</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <?= $this->form()->openTag($frm) ?>
                        <div class="box box-primary">
                            <div class="box-header"><h3 class="box-title">Informasi Wajib Pajak</h3></div>
                            <div class="box-body">
                                <div>&nbsp;&nbsp;</div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Tanggal Validasi</label>
                                        <div class="col-sm-2" style="margin-left:-15px;">
                                            <?= $this->formInput($frm->get('t_tglverifikasispt')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="display: none;">Kode Bayar Bank</label>
                                        <div class="col-sm-2" style="display: none;">
                                            <?= $this->formRow($frm->get('t_kodebayarbanksppt')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">No. Pendaftaran</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kohirpembayaran')) ?>
                                            <?= $this->formInput($frm->get('t_idpembayaranspt')) ?>
                                            <?= $this->formInput($frm->get('t_idspt')) ?>
                                        </div>
                                        <div class="col-sm-1">
                                            <button type="button" class="btn btn-warning"
                                                    data-toggle="modal" data-target="#ModalCari" onclick="calldatagrid();">Cari</button>
                                        </div>
                                    </div>
                                </div>  
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Nama Notaris</label>
                                        <div class="col-sm-4">
                                            <?= $this->formInput($frm->get('t_idnotarisspt')) ?>
                                            <?= $this->formRow($frm->get('s_namanotaris')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NIK</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_nikwppembeli')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">NPWP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_npwpwppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Nama WP</label>
                                        <div class="col-sm-6">
                                            <?= $this->formRow($frm->get('t_namawppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Alamat</label>
                                        <div class="col-sm-6">
                                            <?= $this->formRow($frm->get('t_alamatwppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">RT</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rtwppembeli')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">RW</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rwwppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Kelurahan/Desa</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kelurahanwppembeli')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kecamatan</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kecamatanwppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Kabupaten/Kota</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kabkotawppembeli')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kode Pos</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kodeposwppembeli')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="inputType" class="col-md-2">No. Telp.</label>
                                        <div class="col-md-2">
                                            <?= $this->formRow($frm->get('t_telponwppembeli')) ?>
                                        </div>
                                        <div class="col-md-8" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="box box-success">
                            <div class="box-header"><h3 class="box-title">Informasi Objek Pajak</h3></div>
                            <div class="box-body">
                                <div>&nbsp;&nbsp;</div>       
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NOP/Tahun SPPT</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_nopbphtbsppt')) ?>
                                        </div>
                                        <div class="col-sm-1">
                                            <?= $this->formRow($frm->get('t_thnsppt')) ?>
                                        </div>
                                        <label  class="col-sm-3 control-label">Lakukan
                                            Pemeriksaan OP</label>
                                        <div class="col-sm-1">
                                            <?= $this->formRow($frm->get('t_pemeriksaanop')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Letak Tanah/Bangunan</label>
                                        <div class="col-sm-4">
                                            <?= $this->formRow($frm->get('t_alamatop')) ?>
                                        </div>
                                    </div>
                                </div>       
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">RT</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rtop')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">RW</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rwop')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Kelurahan/Desa</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kelurahanop')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kecamatan</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kecamatanop')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">Kabupaten</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_kabupatenop')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Luas Tanah (Bumi)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_luastanah')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="font-size: 12px">Nilai Pasar/NJOP (m2)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_njoptanah')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">Total</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_totalnjoptanah')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Luas Bangunan</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_luasbangunan')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="font-size: 12px">Nilai Pasar/NJOP (m2)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_njopbangunan')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">Total</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_totalnjopbangunan')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-9 control-label" style="text-align: right;">NJOP PBB</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_grandtotalnjop')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-9 control-label" style="text-align: right;">Harga Transaksi / Nilai Pasar</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_nilaitransaksispt')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Harga Acuan</label>
                                        <div class="col-sm-3">       
                                            <?= $this->formRow($frm->get('s_permetertanah')) ?>
                                        </div>
                                        <div id="analisishargaacuan">
                                            <?= $frm->get('analisishargaacuan')->getValue(); ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">History NJOP Tanah</label>
                                        <div class="col-sm-3">             
                                            <?= $this->formRow($frm->get('historynjoptanah')) ?>
                                        </div>
                                        <div id="analisisharganjoptanah">
                                            <?= $frm->get('analisisharganjoptanah')->getValue(); ?>  
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Jenis Transaksi</label>
                                        <div class="col-sm-3">               
                                            <?= $this->formRow($frm->get('s_namajenistransaksi')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kepemilikan</label>
                                        <div class="col-sm-3">               
                                            <?= $this->formRow($frm->get('s_namahaktanah')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label" style="text-align: left">No. Dokumen Peralihan Hak</label>
                                        <div class="col-sm-3">               
                                            <?= $this->formRow($frm->get('t_nosertifikathaktanah')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="text-align: left">Tgl. Dokumen Peralihan Hak</label>
                                        <div class="col-sm-3">               
                                            <?= $this->formRow($frm->get('t_tglajb')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label" style="text-align:left">No. AJB (Baru)</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_noajbbaru')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="text-align:left">Tgl. AJB (Baru)</label>
                                        <div class="col-sm-2">
                                            <?php
                                            $frm->get('t_tglajbbaru')->setAttribute('onchange', 'hitungBphtb()');
                                            $frm->get('t_tglajbbaru')->setAttribute('onblur', 'hitungBphtb()');
                                            $frm->get('t_tglajbbaru')->setAttribute('value', '');
                                            ?>
                                            <?= $this->formRow($frm->get('t_tglajbbaru')) ?>
                                        </div>
                                        <div class="col-sm-3" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="box box-info">
                            <div class="box-header"><h3 class="box-title">Informasi Perhitungan BPHTB</h3></div>
                            <div class="box-body">
                                <div>&nbsp;&nbsp;</div>            
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label" style="text-align:left">NPOP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_npopspt')) ?>
                                        </div>
                                    </div>
                                </div>             
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label" style="text-align:left">NPOPTKP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_potonganspt')) ?>
                                        </div>
                                    </div>
                                </div>                    
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label" style="text-align:left">NPOPKP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_npopkpspt')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Tarif (%)</label>
                                        <div class="col-sm-1">
                                            <?= $this->formRow($frm->get('t_persenbphtb')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="inputKey" class="col-md-3 control-label" style="text-align: left;">BPHTB yang harus dibayar</label>
                                        <div class="col-md-3">
                                            <?= $this->formRow($frm->get('t_totalspt')) ?>
                                        </div>
                                        <div class="col-md-6" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label" style="text-align:left;">Denda/Sanksi</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_dendaspt')) ?>
                                            <?= $this->formRow($frm->get('t_bulandendaspt')) ?>
                                        </div>
                                        <div class="col-sm-6" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-3 control-label" style="text-align:left;">TOTAL</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_grandtotalspt')) ?>                                            
                                        </div>
                                        <div class="col-sm-6" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="box box-warning">
                            <div class="box-header"><h3 class="box-title">Informasi Penjual</h3></div>
                            <div class="box-body">
                                <div>&nbsp;&nbsp;</div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NIK</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_nikwppenjual')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">NPWP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('t_npwpwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Nama Penjual</label>
                                        <div class="col-sm-6">
                                            <?= $this->formRow($frm->get('t_namawppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Alamat</label>
                                        <div class="col-sm-6">
                                            <?= $this->formRow($frm->get('t_alamatwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">RT</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rtwppenjual')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">RW</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_rwwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Kelurahan/Desa</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kelurahanwppenjual')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kecamatan</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kecamatanwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Kabupaten/Kota</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kabkotawppenjual')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Kode Pos</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('t_kodeposwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="inputType" class="col-md-2">No. Telpon</label>
                                        <div class="col-md-2">
                                            <?= $this->formRow($frm->get('t_telponwppenjual')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="inputKey" class="col-md-2 control-label" style="text-align: left;">Status Pembayaran</label>
                                        <div class="col-md-2">
                                            <?= $this->formRow($frm->get('t_statusbayarspt')) ?>
                                        </div>
                                        <label for="inputValue" class="col-md-2 control-label">Tanggal Pembayaran</label>
                                        <div class="col-md-2">
                                            <?= $this->formRow($frm->get('t_tanggalpembayaran')) ?>
                                        </div>
                                        <div class="col-md-4" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="box box-danger" id="ObjekPemeriksaan">
                            <div class="box-header"><h3 class="box-title">Informasi Objek Pajak <span class="badge bg-red-active">Pemeriksaan</span></h3></div>
                            <div class="box-body">
                                <div>&nbsp;&nbsp;</div>                
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Luas Tanah (Bumi)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('p_luastanah')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="font-size: 12px">Nilai Pasar/NJOP (m2)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('p_njoptanah')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">Total</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_totalnjoptanah')) ?>
                                        </div>
                                    </div>
                                </div>                
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">Luas Bangunan</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('p_luasbangunan')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label" style="font-size: 12px">Nilai Pasar/NJOP (m2)</label>
                                        <div class="col-sm-2">
                                            <?= $this->formRow($frm->get('p_njopbangunan')) ?>
                                        </div>
                                        <label  class="col-sm-1 control-label">Total</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_totalnjopbangunan')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-9 control-label" style="text-align: right;">NJOP PBB</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_grandtotalnjop')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-9 control-label" style="text-align: right;">Harga Transaksi / Nilai Pasar</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_nilaitransaksispt')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NPOP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_npop')) ?>
                                        </div>
                                    </div>
                                </div>         
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NPOPTKP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_potonganspt')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">NPOPKP</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_npopkp')) ?>
                                        </div>
                                        <label  class="col-sm-2 control-label">Tarif
                                            (%)</label>
                                        <div class="col-sm-1">
                                            <?= $this->formRow($frm->get('p_persenbphtb')) ?>
                                        </div>
                                    </div>
                                </div>                 
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label  class="col-sm-2 control-label">BPHTB Terhutang</label>
                                        <div class="col-sm-3">
                                            <?= $this->formRow($frm->get('p_totalspt')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="inputKey" class="col-md-2 control-label" style="text-align: left;">Jenis Transaksi</label>
                                        <div class="col-md-3">
                                            <?= $this->formRow($frm->get('p_namajenistransaksi')) ?>
                                        </div>
                                        <label for="inputValue" class="col-md-2 control-label">Kepemilikan</label>
                                        <div class="col-md-3">
                                            <?= $this->formRow($frm->get('p_namahaktanah')) ?>
                                        </div>
                                        <div class="col-md-2" style="text-align: right">

                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>

                        <div class="box box-default">
                            <div class="box-header"><h3 class="box-title">Persyaratan</h3></div>
                            <div class="box-body">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <div id="persyaratannya">
                                                <?= $this->formRow($frm->get('t_persyaratan')) ?>                                            
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div id="persyaratannya">
                                                <label>Persyaratan Validasi</label>
                                                <?= $this->formRow($frm->get('t_persyaratanverifikasi')) ?>                                            
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <div class="col-md-12" style="text-align: right">
                                            <input type="submit" value="Proses" onclick="this.disabled = true" class="btn btn-success">  <a href="<?=$this->url('verifikasi_spt')?>" class="btn btn-warning">Kembali</a>
                                        </div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                        <?= $this->form()->closeTag($frm) ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Modal Cari -->
<div class="modal fade" id="ModalCari" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Daftar Pendaftaran SSPD BPHTB</h4>
            </div>
            <div class="modal-body" id="dialog_pendataan" title="Daftar Pendataan">
                <div>
                    <table class="table table-bordered table-responsive table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    No.<br/>Pendaftaran
                                </th>
                                <th class="text-center">
                                    Tanggal<br/>Pendaftaran
                                </th>
                                <th class="text-center" style="vertical-align: middle">
                                    NOP
                                </th>
                                <th class="text-center">
                                    Nama Pembeli<br/>(Wajib Pajak)
                                </th>
                                <th class="text-center" style="vertical-align: middle">
                                    Nama Penjual
                                </th>
                                <th class="text-center" style="vertical-align: middle">
                                    Pilihan
                                </th>
                            </tr>
                        </thead>
                        <tbody id="listpendataan">

                        </tbody>
                        <tfoot>              
                            <tr>
                                <td colspan="6" class="text-center">
                                    <div class="row">
                                        <div class="col-sm-4 text-left">Jumlah Baris Ditampilkan: <input type="text" id="rows" style="width: 20%" class="text-center" value="10"></div>
                                        <div class="col-sm-3">
                                            <a href="#" onclick="calldatagrid(1);return false;"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a>

                                            <input type="text" id="page" value="1" style="width: 20%" class="text-center">

                                            <a href="#" onclick="calldatagrid(2);return false;"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="col-sm-5 text-right">
                                            <p>Jumlah Data <span id="total_data"></span>&nbsp;Jumlah Halaman <span id="total_halaman"></span></p>                                    
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Tunggakan PBB -->
<div class="modal fade" id="ModalTunggakanPBB" tabindex="-1"
     role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel" style="color: red"><b>Peringatan !!! PBB Belum Lunas</b></h4>
            </div>
            <div class="modal-body" id="dialog_pendataan" title="Daftar Pendataan">
                <div id="datatunggakan"></div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" onclick="tutupmodaltunggakan()">Tutup</button>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    .form-group{
        margin: 0px;
    }
</style>
<script type="text/javascript">

    jQuery("#t_tglverifikasispt").datepicker({
        format: 'dd-mm-yyyy',
        startDate: '01-01-2000',
        endDate: '0d',
        autoclose: true,
        daysOfWeekDisabled: '06',
        language: 'id'
    });
    $(function () {
        pilihPendataanSspdBphtb($('#t_idspt').val());
//        datanop();
        
    });
    //Keterangan Waris
    $("#ketwaris").hide();
    function myFunction() {
        $("#ketwaris").show();
    }
    function myFunction1() {
        $("#ketwaris").hide();
    }

    //Form Pemeriksaan Objek Pajak
<?php
if ($t_pemeriksaanop == 1) {
    ?>
        $("#ObjekPemeriksaan").show();
                <?php } else {
        ?>
                $("#ObjekPemeriksaan").hide();
<?php } ?>

    function FungsiPemeriksaanOP() {
        $("#ObjekPemeriksaan").show();
        $('#p_luastanah').val($("#t_luastanah").val());
        $('#p_njoptanah').val($("#t_njoptanah").val());
        $('#p_totalnjoptanah').val($("#t_totalnjoptanah").val());
        $('#p_luasbangunan').val($("#t_luasbangunan").val());
        $('#p_njopbangunan').val($("#t_njopbangunan").val());
        $('#p_totalnjopbangunan').val($("#t_totalnjopbangunan").val());
        $('#p_grandtotalnjop').val($("#t_grandtotalnjop").val());
        $('#p_nilaitransaksispt').val($("#t_nilaitransaksispt").val());
        $('#p_namajenistransaksi').val($("#s_namajenistransaksi").val());
        $('#p_namahaktanah').val($("#s_namahaktanah").val());
        $('#p_npop').val($("#t_npopspt").val());
        $('#p_potonganspt').val($("#t_potonganspt").val());
        $('#p_npopkp').val($("#t_npopkpspt").val());
        $('#p_persenbphtb').val($("#t_persenbphtb").val());
        $('#p_totalspt').val($("#t_totalspt").val());
    }
    function FungsiPemeriksaanOP1() {
        $("#ObjekPemeriksaan").hide();
        $('#p_luastanah').val('');
        $('#p_njoptanah').val('');
        $('#p_totalnjoptanah').val('');
        $('#p_luasbangunan').val('');
        $('#p_njopbangunan').val('');
        $('#p_totalnjopbangunan').val('');
        $('#p_grandtotalnjop').val('');
        $('#p_nilaitransaksispt').val('');
        $('#p_namajenistransaksi').val('');
        $('#p_namahaktanah').val('');
        $('#p_terbukti').val('');
        $('#p_ketwaris').val('');
        $('#p_potonganspt').val('');
        $('#p_totalspt').val('');
    }

    function next(a) {
        jQuery('#tabs a[href=#' + a + ']').tab('show');
    }

    function cekvaliditassspd() {

    }

    function clearForm() {
        $('#t_idspt').val("");
        $('#t_kohirpembayaran').val("");
        //data wp
        $('#t_namawppembeli').val("");
        $('#t_nikwppembeli').val("");
        $('#t_npwpwppembeli').val("");
        $('#t_alamatwppembeli').val("");
        $('#t_rtwppembeli').val("");
        $('#t_rwwppembeli').val("");
        $('#t_kecamatanwppembeli').val("");
        $('#t_kelurahanwppembeli').val("");
        $('#t_kabkotawppembeli').val("");
        $('#t_telponwppembeli').val("");
        $('#t_kodeposwppembeli').val("");
        //data nop 
        $('#t_nopbphtbsppt').val("");
        $('#t_thnsppt').val("");
        $('#t_alamatop').val("");
        $('#t_rtop').val("");
        $('#t_rwop').val("");
        $('#t_kelurahanop').val("");
        $('#t_kecamatanop').val("");
        $('#t_kabupatenop').val("");
        $('#t_nosertifikathaktanah').val("");
        $('#t_totalspt').val("");
        $('#t_luastanah').val("");
        $('#t_luasbangunan').val("");
        $('#t_totalnjoptanah').val("");
        $('#t_totalnjopbangunan').val("");
        $('#t_njoptanah').val("");
        $('#t_njopbangunan').val("");
        $('#t_grandtotalnjop').val("");
        $('#t_nilaitransaksispt').val("");
        $('#t_idjenistransaksi').val("");
        $('#t_idjenishaktanah').val("");
        $('#t_potonganspt').val("");
        $('#t_nilaipembayaranspt').val("");
        //data penjual
        $('#t_namawppenjual').val("");
        $('#t_nikwppenjual').val("");
        $('#t_alamatwppenjual').val("");
        $('#t_kelurahanwppenjual').val("");
        $('#t_kecamatanwppenjual').val("");
        $('#t_kabkotawppenjual').val("");
        $('#t_kodeposwppenjual').val("");
        $('#t_telponwppenjual').val("");
        //data pembayaran
        $('#t_idpembayaranspt').val("");
        $('#t_tanggalpembayaran').val("");
        $('#t_statusbayarspt').val("");
    }

    function pilihPendataanSspdBphtb(a) {
        $.post('<?= $this->url() ?>/pilihPendataanSspdBphtb', {t_idspt: a}, function (data) {
            var aa = JSON.parse(data);
            $('#t_idspt').val(aa.t_idspt);
            $('#t_idnotarisspt').val(aa.t_idnotarisspt);
            $('#t_kohirpembayaran').val(aa.t_kohirspt);
            //data wp
            $('#t_namawppembeli').val(aa.t_namawppembeli);
            $('#t_nikwppembeli').val(aa.t_nikwppembeli);
            $('#t_npwpwppembeli').val(aa.t_npwpwppembeli);
            $('#t_alamatwppembeli').val(aa.t_alamatwppembeli);
            $('#t_rtwppembeli').val(aa.t_rtwppembeli);
            $('#t_rwwppembeli').val(aa.t_rwwppembeli);
            $('#t_kecamatanwppembeli').val(aa.t_kecamatanwppembeli);
            $('#t_kelurahanwppembeli').val(aa.t_kelurahanwppembeli);
            $('#t_kabkotawppembeli').val(aa.t_kabkotawppembeli);
            $('#t_telponwppembeli').val(aa.t_telponwppembeli);
            $('#t_kodeposwppembeli').val(aa.t_kodeposwppembeli);
            //data nop 
            $('#t_nopbphtbsppt').val(aa.t_nopbphtbsppt);
            $('#t_thnsppt').val(aa.t_thnsppt);            
            $('#t_alamatop').val(aa.t_alamatop);
            $('#t_rtop').val(aa.t_rtop);
            $('#t_rwop').val(aa.t_rwop);
            $('#t_kelurahanop').val(aa.t_kelurahanop);
            $('#t_kecamatanop').val(aa.t_kecamatanop);
            $('#t_luastanah').val(aa.t_luastanah);
            $('#t_njoptanah').val(aa.t_njoptanah);
            $('#t_totalnjoptanah').val(aa.t_totalnjoptanah);
            $('#t_luasbangunan').val(aa.t_luasbangunan);
            $('#t_njopbangunan').val(aa.t_njopbangunan);
            $('#t_totalnjopbangunan').val(aa.t_totalnjopbangunan);
            $('#t_grandtotalnjop').val(aa.t_grandtotalnjop);
            $('#t_nilaitransaksispt').val(aa.t_nilaitransaksispt);
            $('#t_idjenistransaksi').val(aa.t_idjenistransaksi);
            $('#t_idjenishaktanah').val(aa.t_idjenishaktanah);
            $('#t_nosertifikathaktanah').val(aa.t_nosertifikathaktanah);
            $("#t_tglajb").val(aa.t_tglajb);
            $("#t_tglajbbaru").val(aa.t_tglajbbaru);
            $("#t_noajbbaru").val(aa.t_noajbbaru);
            //data perhitungan bphtb            
            //var npopkp = aa.t_totalspt / 5 * 100;
            //var npop = (npopkp * 1) + aa.t_potonganspt;
            $('#t_npopspt').val(aa.npop);
            $('#t_potonganspt').val(aa.t_potonganspt);
            $('#t_npopkpspt').val(aa.npopkp);
            $('#t_totalspt').val(aa.t_totalspt);
            $("#t_dendaspt").val(aa.t_dendaspt);
            $("#t_bulandendaspt").val(aa.t_bulandendaspt);            
            $("#t_grandtotalspt").val(aa.grand_total_pajak);
//            datanop(aa.t_nopbphtbsppt, aa.t_thnsppt);
            //data penjual
            $('#t_namawppenjual').val(aa.t_namawppenjual);
            $('#t_nikwppenjual').val(aa.t_nikwppenjual);
            $('#t_alamatwppenjual').val(aa.t_alamatwppenjual);
            $('#t_kelurahanwppenjual').val(aa.t_kelurahanwppenjual);
            $('#t_kecamatanwppenjual').val(aa.t_kecamatanwppenjual);
            $('#t_kabkotawppenjual').val(aa.t_kabkotawppenjual);
            $('#t_kodeposwppenjual').val(aa.t_kodeposwppenjual);
            $('#t_telponwppenjual').val(aa.t_telponwppenjual);
            //data pembayaran
            $('#t_idpembayaranspt').val(aa.t_idpembayaranspt);
            //data persyaratan            
            $('#persyaratannya').html(aa.t_persyaratan);
            //$('#persyaratannyaverifikasi').html(aa.t_persyaratanverifikasi);
//            if (aa.t_tanggalpembayaran) {
//                $('#t_tanggalpembayaran').val(xx);
//            } else {
//                $('#t_tanggalpembayaran').val("-");
//            }

            if (aa.t_statusbayarspt == true) {
                $('#t_statusbayarspt').val("Sudah Dibayarkan");
            } else {
                $('#t_statusbayarspt').val("Belum Dibayarkan");
            }
            cektunggakanpbb();
            jQuery('#ModalCari').modal('hide');
            cekvaliditassspd();
        });
    }

    function cektunggakanpbb() {
        $.post('<?= $this->url('verifikasi_spt') ?>/cektunggakanpbb', {t_nopbphtbsppt: $('#t_nopbphtbsppt').val()}, function (data) {
            var aa = JSON.parse(data);
            if (aa.PBB_YG_HARUS_DIBAYAR_SPPT != '') {
                jQuery('#ModalTunggakanPBB').modal('show');
                $('#datatunggakan').html(aa.datatunggakan);
            } else {
                alert('Tidak Ada Tunggakan');
            }
        });
    }

    function tutupmodaltunggakan() {
        jQuery('#ModalTunggakanPBB').modal('hide');
    }

    function hitungnjop() {
        $.post('<?= $this->url() ?>/hitungnjop', {
            p_luastanah: $('#p_luastanah').val(), p_luasbangunan: $('#p_luasbangunan').val(), p_njoptanah: $('#p_njoptanah').val(),
            p_njopbangunan: $('#p_njopbangunan').val(), p_nilaitransaksispt: $('#p_nilaitransaksispt').val(), p_potonganspt: $('#p_potonganspt').val()
            , p_persenbphtb: $('#p_persenbphtb').val()
        }, function (data) {
            var aa = JSON.parse(data);
            $("#p_totalnjoptanah").val(aa.p_totalnjoptanah * 1);
            $('#p_totalnjopbangunan').val(aa.p_totalnjopbangunan * 1);
            $('#p_grandtotalnjop').val(aa.p_grandtotalnjop * 1);
            $('#p_npop').val(aa.p_npop * 1);
            $('#p_potonganspt').val(aa.p_potonganspt * 1);
            $('#p_npopkp').val(aa.p_npopkp * 1);
            $('#p_totalspt').val(aa.p_totalspt * 1);
        });
    }

    function datanop(a, b) {
        $.post('<?= $this->url('pendataan_sspd') ?>/datanop', {t_nopbphtbsppt: a, t_thnsppt: b}, function (data) {
            var aa = JSON.parse(data);
            //Data Objek Pajak
            $('#t_namasppt').val(aa.NM_WP_SPPT);
            $('#t_alamatop').val(aa.JALAN_OP);
            $('#t_rtop').val(aa.RT_OP);
            $('#t_rwop').val(aa.RW_OP);
            $('#t_kelurahanop').val(aa.NM_KELURAHAN);
            $('#t_kecamatanop').val(aa.NM_KECAMATAN);
            //Data Penjual
            $('#t_namawppenjual').val(aa.NM_WP_SPPT);
            $('#t_alamatwppenjual').val("Jl. " + aa.JLN_WP_SPPT + " Blok " + aa.BLOK_KAV_NO_WP_SPPT + " Rt. " + aa.RT_WP_SPPT + " Rw. " + aa.RW_WP_SPPT);
            $('#t_kelurahanwppenjual').val(aa.KELURAHAN_WP_SPPT);
            $('#t_kabkotawppenjual').val(aa.KOTA_WP_SPPT);
            $('#t_kodeposwppenjual').val(aa.KD_POS_WP_SPPT);
        });
    }
    
    function calldatagrid(direction) {
        datagrid($("#page").val(), $("#rows").val(), direction);
    }

    function datagrid(page, row, direction) {
        $.get('<?= $this->url() ?>/dataGridPendataanBphtb/'  + page + '/' + row + '/' + direction , function (data) {
            var aa = JSON.parse(data)
            $("#listpendataan").html(aa.grid);
//            $("#rows").val(aa.rows);
//            $("#page").val(aa.page);
//            $("#total_data").html(": " + aa.count);
//            $("#total_halaman").html(": " + aa.total_halaman);
        });
    }
</script>
<style>
    .radio_render{

    }

    .radio_render label {
        width: 100%;
        float: left;
    }

    .radio_render label input {
        margin-top: -2.5px;
    }

</style>