<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <span style="font-size: 15px">VALIDASI</span>
                                        <div class="pull-right">
                                            <a href="<?= $this->url('verifikasi_spt') ?>/tambah" class="btn bg-purple btn-sm btn-flat">
                                                <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;Proses Validasi
                                            </a>
                                            <div class="btn-group">
                                                <button data-toggle="dropdown" class="btn btn-success btn-flat btn-sm dropdown-toggle" type="button">
                                                    <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Cetak&nbsp;&nbsp;
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul role="menu" class="dropdown-menu pull-right bg-green">
                                                    <li>
                                                        <a href="#" style="color: black" onclick="openCetak2()">Cetak K. Bayar</a>
                                                    </li>
                                                    <li>
                                                        <a href="#" style="color: black" onclick="openCetakDaftarVerifikasi()">Cetak Daftar Validasi</a>  
                                                    </li>                     
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row" style="margin-top: 10px;margin-bottom: 10px">
                                    <div class="col-sm-2">
                                        <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                            <option value="">Pilih Pencarian</option>
                                            <option value="t_kodebayarbanksppt">Kode Bayar</option>
                                            <option value="t_kohirspt">No. Pendaftaran</option>
                                            <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                            <option value="t_periodespt">Periode Pajak</option>
                                            <option value="t_kohirketetapanspt">No. SSPD</option>
                                            <option value="t_nopbphtbsppt">NOP</option>
                                            <option value="t_namawppembeli">Nama WP</option>
                                            <option value="t_totalspt">Jumlah Pajak</option>
                                            <option value="t_dendaspt">Jumlah Denda</option>
                                            <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="input-group input-group-sm">
                                            <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                            <div class="input-group-btn combooperatorc">
                                                <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                                    <option value="">Pilih</option>
                                                    <option value="carisama">=</option>
                                                    <option value="carilike">like</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                                <option value="t_kodebayarbanksppt">Kode Bayar</option>
                                                <option value="t_kohirspt">No. Pendaftaran</option>
                                                <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                                <option value="t_periodespt">Periode Pajak</option>
                                                <option value="t_kohirketetapanspt">No. SSPD</option>
                                                <option value="t_nopbphtbsppt">NOP</option>
                                                <option value="t_namawppembeli">Nama WP</option>
                                                <option value="t_totalspt">Jumlah Pajak</option>
                                                <option value="t_dendaspt">Jumlah Denda</option>
                                                <option value="s_namajenistransaksi">Jenis Transaksi</option>
                                            </select>
                                        </span>
                                    </div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <div class="form-inline">
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                                        Asc
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                                        Desc
                                                    </label>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div style=" overflow: auto;">
                                        <div class="col-lg-12 col-sm12">
                                            <div class="unseen no-more-tables">
                                                <table class="table table-striped table-hover table-bordered" style="font-size: 12px">
                                                    <thead>
                                                        <tr class="bg-blue">  
                                                            <th class="text-center" style="width: 5%">
                                                                No. Daftar
                                                            </th>           
                                                            <th class="text-center" style="width: 5%">
                                                                Tahun Pajak
                                                            </th>     
                                                            <th class="text-center" style="width: 10%">
                                                                Tgl. Validasi
                                                            </th>     
                                                            <th class="text-center">
                                                                Nama WP
                                                            </th>     
                                                            <th class="text-center">
                                                                Jenis Transaksi
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Validasi
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Kode Bayar
                                                            </th>     
                                                            <th class="text-center" style="width: 7%">
                                                                Pembayaran
                                                            </th>     
                                                            <th class="text-center" style="width: 18%">
                                                                Cetak
                                                            </th>           
                                                            <th class="text-center" style="width: 10%">
                                                                Pilihan
                                                            </th>  
                                                        </tr>
                                                    </thead>
                                                    <tbody id="body_grid">
                                                    </tbody>
                                                    <tfoot>              
                                                        <tr>
                                                            <td colspan="12" class="text-center">
                                                                <div class="row">
                                                                    <div class="col-sm-3 text-left">
                                                                        <span class="hiddene">
                                                                            <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                                                <option value="10">10</option>
                                                                                <option value="20">20</option>
                                                                                <option value="30">30</option>
                                                                                <option value="40">40</option>
                                                                                <option value="50">50</option>
                                                                            </select>
                                                                        </span>
                                                                    </div>
                                                                    <div class="col-sm-6" style="text-align: center">
                                                                        <center>
                                                                            <div id="paginatore"></div>
                                                                            <input type="hidden" id="page" value="1">
                                                                        </center>
                                                                    </div>
                                                                    <div class="col-sm-3 text-right">
                                                                        <span class="hiddene">
                                                                            <p>
                                                                                <b><span id="awaldata"></span>-<span id="akhirdata"></span>/<span id="total_data"></span> Data</b>
                                                                            </p>                 
                                                                        </span>                   
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </tfoot>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK KODE BAYAR</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" id="kb_periode_spt" value="<?= date('Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" id="kb_tgl_cetak" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor SSPD
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" id="kb_no_spt1" class="form-control">
                                </div>
                                <div class="col-md-1">S/d</div>
                                <div class="col-sm-4">
                                    <input type="text" id="kb_no_spt2" class="form-control">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>      
            </div>
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutup2()"><i class="glyphicon glyphicon-circle-arrow-left"></i> Tutup</button>
                    <button class="btn btn-danger btn-sm btn-flat" onclick="cetakkodebyr();"><i class="fa fa-fw fa-file-pdf-o"></i> CETAK PDF</button>
                </div>
            </div>            
        </div>
    </div>
</div>

<div class="modal fade" id="cetakbuktilengkap" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK BUKTI LENGKAP</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="periode_spt" value="<?= date('Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" name="tgl_cetak" id="tgl_cetak" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor Pendaftaran
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="no_spt1" class="form-control"  readonly>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mengetahui 
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuilengkap" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuilengkap as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                </table>
            </div> 
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutup()">Tutup</button>
                    <button class="btn btn-danger btn-sm btn-flat" onclick="cetakbuktilengkap1();"><i class="fa fa-fw fa-file-pdf-o"></i> Cetak</button>
                </div>
            </div>                
        </div>
    </div>
</div>


<div class="modal fade" id="cetakbuktipenerimaan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK MELENGKAPI BERKAS</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="periode_spt_bukti" value="<?= date('Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" name="tgl_cetak_bukti" id="tgl_cetak_bukti" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            No. Pendaftaran
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="no_spt_bukti1" class="form-control"  readonly>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mengetahui 
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuibphtb" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuibphtb as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                </table>
                <div align="right">
                    <button class="btn btn-success" onclick="cetakbuktipenerimaan();">Cetak</button> <button class="btn btn-success" onclick="tutupbukti()">Tutup</button>
                </div>                
            </div>            
        </div>
    </div>
</div>

<div class="modal fade" id="myModalDaftarValidasi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK DAFTAR VALIDASI</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width: 30%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="periode_sptverifikasi" value="<?= date('Y') ?>">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="tgl_cetakverifikasi" value="<?= date('d-m-Y') ?>">
                                </div>
                            </div>    
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Validasi
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="tgl_verifikasi1" value="<?= date('d-m-Y') ?>">
                                </div>
                                <div class="col-sm-1">S/d</div>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" id="tgl_verifikasi2" value="<?= date('d-m-Y') ?>">
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>  
            </div> 
            <div class="modal-footer">
                <div class="col-sm-12">
                    <button class="btn btn-primary btn-sm btn-flat pull-left" onclick="tutupCetakDaftarVerifikasi()"><i class="glyphicon glyphicon-circle-arrow-left"></i> Tutup</button>
                    <button class="btn btn-success btn-sm btn-flat" onclick="cetakDaftarValidasi();">
                        <span class="glyphicon glyphicon-print"></span> Cetak
                    </button>
                </div>
            </div>            
        </div>
    </div>
</div>

<div class="modal fade" id="cetaksuratpenelitian" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CETAK SURAT PENELITIAN LAPANGAN</h4>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <td style="width:40%">
                            Tahun Pajak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="periode_sptpenelitian" value="<?= date('Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Tanggal Cetak
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="tgl_cetakpenelitian" value="<?= date('d-m-Y') ?>" class="form-control">
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nomor Pendaftaran
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <input type="text" id="no_sptpenelitian" class="form-control"  readonly>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Pemeriksan Lap 
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian1" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian1 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian2" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian2 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian3" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian3 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian4" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian4 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mengetahui I
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian5" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian5 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Mengetahui II
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm-12">
                                    <select id="mengetahuipenelitian6" class="selectpicker" data-live-search="true">
                                        <?php foreach ($this->data_mengetahuipenelitian6 as $k => $v) { ?>
                                            <option value="<?= $v['s_idpejabat'] ?>"><?= $v['s_namapejabat'] ?> - <?= $v['s_jabatanpejabat'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div> 
                        </td>
                    </tr>
                </table>
                <div align="right">
                    <button class="btn btn-success" onclick="cetaksuratpenelitian();">Cetak</button> <button class="btn btn-success" onclick="tutup()">Tutup</button>
                </div>                
            </div>            
        </div>
    </div>
</div>

<style type="text/css">
    @media only screen and (max-width: 800px) {
        .unseen table td:nth-child(2), 
        .unseen table td:nth-child(3), 
        .unseen table td:nth-child(5), 
        .unseen table td:nth-child(6), 
        .unseen table td:nth-child(8), 
        .unseen table td:nth-child(9), 
        .unseen table th:nth-child(9) {display: none;}
        .hiddene {display: none;}
    }
</style>
<script type="text/javascript">
    $(function () {
        calldatagrid();
    });

    $("#t_periodespt").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#t_tglverifikasispt").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapus/' + a);
            calldatagrid();
        }
        calldatagrid();
    }
    
    function cetaksspd() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetaksspdbphtb?no_spt1=' + $("#no_spt1").val() + "&no_spt2=" + $("#no_spt2").val() + "&periode_spt=" + $("#periode_spt").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetak").val())
    }

//  ======================================================
//  Cetak Kode Bayar

    jQuery("#kb_tgl_cetak").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    $("#kb_periode_spt").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    function openCetak2() {
        jQuery('#myModal2').modal('show');
    }

    function tutup2() {
        jQuery('#myModal2').modal('hide');
        jQuery("#kb_no_spt1,#kb_no_spt2").val('');
    }

    function cetakkodebyr() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetakkodebayar?no_spt1=' + $("#kb_no_spt1").val() + "&no_spt2=" + $("#kb_no_spt2").val() + "&periode_spt=" + $("#kb_periode_spt").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#kb_tgl_cetak").val())
    }

//  ======================================================

//  ======================================================    
//  Cetak Bukti Lengkap
    $("#periode_spt").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetak").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function openCetak(a) {
        jQuery('#cetakbuktilengkap').modal('show');
        jQuery("#no_spt1").val(a);
    }

    function tutup() {
        jQuery('#cetakbuktilengkap').modal('hide');
        jQuery("#no_spt1").val('');
    }

    function cetakbuktilengkap1() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetakbuktipenerimaanvalidasi?no_spt1=' + $("#no_spt1").val() + "&periode_spt=" + $("#periode_spt_bukti").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetak_bukti").val() + "&mengetahuibphtb=" + $("#mengetahuilengkap").val())
    }
//  =======================================================


//  =======================================================
//  Cetak Melengkapi Berkas
    $("#periode_spt_bukti").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetak_bukti").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function openCetakBukti(a) {
        jQuery('#cetakbuktipenerimaan').modal('show');
        jQuery("#no_spt_bukti1").val(a);
    }

    function tutupbukti() {
        jQuery('#cetakbuktipenerimaan').modal('hide');
        jQuery("#no_spt_bukti1").val('');
    }

    function cetakbuktipenerimaan() {
        window.open('<?= $this->url('cetak_sspd') ?>/cetakbuktipenerimaanvalidasi?no_spt1=' + $("#no_spt_bukti1").val() + "&periode_spt=" + $("#periode_spt_bukti").val() + "&t_objekspt=1" + "&tgl_cetak=" + $("#tgl_cetak_bukti").val() + "&mengetahuibphtb=" + $("#mengetahuibphtb").val())
    }

//  =======================================================



//    =====================================================
//    Cetak Daftar Vallidasi

    function openCetakDaftarVerifikasi() {
        jQuery('#myModalDaftarValidasi').modal('show');
    }

    function tutupCetakDaftarVerifikasi() {
        jQuery('#myModalDaftarValidasi').modal('hide');
    }

    $("#periode_sptverifikasi").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetakverifikasi").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_verifikasi1").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#tgl_verifikasi2").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function cetakDaftarValidasi() {
        window.open('<?= $this->url('cetak_laporan') ?>/cetakdaftarverifikasi?periode_spt=' + $("#periode_spt").val() + "&tgl_cetak=" + $("#tgl_cetakverifikasi").val() + "&tgl_verifikasi1=" + $("#tgl_verifikasi1").val() + "&tgl_verifikasi2=" + $("#tgl_verifikasi2").val())
    }

//    =====================================================


//  ======================================================    
//  Cetak Surat Hasil Penelitian Lapangan
    $("#periode_sptpenelitian").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#tgl_cetakpenelitian").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    function openCetakPenelitian(a) {
        jQuery('#cetaksuratpenelitian').modal('show');
        jQuery("#no_sptpenelitian").val(a);
    }

    function tutupCetakPenelitian() {
        jQuery('#cetaksuratpenelitian').modal('hide');
        jQuery("#no_sptpenelitian").val('');
    }

    function cetaksuratpenelitian() {
        window.open('<?= $this->url('verifikasi_spt') ?>/cetaksuratpenelitian?no_sptpenelitian=' + $("#no_sptpenelitian").val() + "&periode_sptpenelitian=" + $("#periode_sptpenelitian").val() + "&tgl_cetakpenelitian=" + $("#tgl_cetakpenelitian").val() + "&mengetahuipenelitian1=" + $("#mengetahuipenelitian1").val() + "&mengetahuipenelitian2=" + $("#mengetahuipenelitian2").val() + "&mengetahuipenelitian3=" + $("#mengetahuipenelitian3").val() + "&mengetahuipenelitian4=" + $("#mengetahuipenelitian4").val() + "&mengetahuipenelitian5=" + $("#mengetahuipenelitian5").val() + "&mengetahuipenelitian6=" + $("#mengetahuipenelitian6").val())
    }
//  =======================================================

</script>
