<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <span style="font-size: 15px">MENU KOREKSI</span>
                                    </div>
                                </div>
                                <div class="row" style="margin-top: 10px;margin-bottom: 10px">
                                    <div class="col-sm-2">
                                        <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                            <option value="">Pilih Pencarian</option>
                                            <option value="t_kohirspt">No. Pendaftaran</option>
                                            <option value="t_tanggalpembayaran">Tgl. Pembayaran</option>
                                            <option value="t_periodepembayaran">Thn. Pembayaran</option>
                                            <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                            <option value="t_namawppembeli">Nama WP</option>
                                            <option value="t_tglverifikasispt">Tgl. Verifikasi</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="input-group input-group-sm">
                                            <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                            <div class="input-group-btn combooperatorc">
                                                <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                                    <option value="">Pilih</option>
                                                    <option value="carisama">=</option>
                                                    <option value="carilike">like</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                                <option value="">Pilih Sorting</option>
                                                <option value="t_kohirspt">No. Pendaftaran</option>
                                                <option value="t_tanggalpembayaran">Tgl. Pembayaran</option>
                                                <option value="t_periodepembayaran">Thn. Pembayaran</option>
                                                <option value="t_tglprosesspt">Tgl. Pendaftaran</option>
                                                <option value="t_namawppembeli">Nama Pembeli</option>
                                                <option value="t_tglverifikasispt">Tgl. Verifikasi</option>
                                            </select>
                                        </span>
                                    </div>
                                    <div class="col-sm-2">
                                        <span class="hiddene">
                                            <div class="form-inline">
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                                        Asc
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <label>
                                                        <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                                        Desc
                                                    </label>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div style=" overflow: auto;">
                                        <div class="col-lg-12 col-sm12">
                                            <table class="table table-hover table-bordered" style="font-size: 12px">
                                                <thead>
                                                    <tr class="bg-blue">  
                                                        <th class="text-center" style="width: 7%">
                                                            No. Daftar
                                                        </th>           
                                                        <th class="text-center" style="width: 7%">
                                                            Thn. Bayar
                                                        </th>     
                                                        <th class="text-center" style="width: 10%">
                                                            Tgl. Daftar
                                                        </th>     
                                                        <th class="text-center">
                                                            Nama WP
                                                        </th>         
                                                        <th class="text-center">
                                                            Validasi
                                                        </th>      
                                                        <th class="text-center">
                                                            Pembayaran
                                                        </th>            
                                                        <th class="text-center">
                                                            Koreksi
                                                        </th> 
                                                    </tr>
                                                </thead>
                                                <tbody id="body_grid">
                                                </tbody>
                                                <tfoot>              
                                                    <tr>
                                                        <td colspan="7" class="text-center">
                                                            <div class="row">
                                                                <div class="col-sm-3 text-left">
                                                                    <span class="hiddene">
                                                                        <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                                            <option value="10">10</option>
                                                                            <option value="20">20</option>
                                                                            <option value="30">30</option>
                                                                            <option value="40">40</option>
                                                                            <option value="50">50</option>
                                                                        </select>
                                                                    </span>
                                                                </div>
                                                                <div class="col-sm-6" style="text-align: center">
                                                                    <center>
                                                                        <div id="paginatore"></div>
                                                                        <input type="hidden" id="page" value="1">
                                                                    </center>
                                                                </div>
                                                                <div class="col-sm-3 text-right">
                                                                    <span class="hiddene">
                                                                        <p>
                                                                            <b><span id="awaldata"></span>-<span id="akhirdata"></span>/<span id="total_data"></span> Data</b>
                                                                        </p>  
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script type="text/javascript">
    $(function () {
        calldatagrid();
    });

    $("#t_periodepembayaran").datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });

    jQuery("#t_tglprosesspt").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#t_tglverifikasispt").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });

    jQuery("#t_tanggalpembayaran").datepicker({
        format: 'dd-mm-yyyy',
        language: 'id'
    });
//  =======================================================
</script>
