<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->prepare();
?>
<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">SETTING KECAMATAN</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="row margin">
                            <div class="col-md-12">
                                <fieldset>                 
                                    <div>
                                        <?= $this->form()->openTag($frm) ?>
                                        <?= $this->formHidden($frm->get('s_idkecamatan')) ?>  
                                        <?= $this->formRow($frm->get('s_kodekecamatan')) ?>
                                        <?= $this->formRow($frm->get('s_namakecamatan')) ?>
                                        <br/>
                                        <div align="right">
                                            <?= $this->formInput($frm->get('simpan')) ?> 
                                            <a href="<?= $this->url('setting_kecamatan_bphtb') ?>" class="btn btn-success">Kembali</a>
                                        </div>
                                        <?= $this->form()->closeTag($frm) ?>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->